### ISSUE TITLE
Machine unresponsive after exiting game

### ISSUE THREAD

**Issue by iggyvolz** [kyechou/leagueoflegends#1]
Apologies if this is unrelated to the launch script but this did show just after upgrading from v0.9.18 to v0.9.22.

After exiting the game, my desktop manager crashes and I am only able to move the mouse.  I have to hard-power-off my machine to restore functionality.

**Comment by kyechou** [comment]
Hi @iggyvolz, I'm not sure about the cause either, since the only difference of the package between the releases is the typo in the registry file getting fixed. Is the issue reproducible after downgrading the package or after you rebooted your machine?

**Comment by iggyvolz** [comment]
Rebooted my machine and retried several times and the issue persisted, ran with the 9.18 patch and the issue did not show up.

**Comment by kyechou** [comment]
It seems like enabling the MouseWarpOverride option would mess up you environment somehow, but I'm unable to reproduce the issue at my end. What was the desktop environment/window manager you were using when the issue happened? And could you give more details about which program crashed and how it crashed? For example, you may ctrl-alt-F2(or F<num>) to a tty and use htop/top/ps to see if there's anything abnormal.
But a simple workaround for your setup may be just not enabling the MouseWarpOverride option.
Also, have you tried to uninstall and reinstall the game after upgrading to v0.9.22?
Thanks.

**Comment by iggyvolz** [comment]
I am using gnome-desktop on Arch Linux:
```$ pacman -Q gnome-desktop
gnome-desktop 1:3.34.1-1```

Installed/upgrading this package via `yay -Syu`.  I manually cloned the directory, checked out the old commit, and ran the package in order to run the old version (because I still haven't figured out how to downgrade on Arch).

Will try to reproduce the crash now.

**Comment by iggyvolz** [comment]
Had to reinstall gnome-desktop this morning because it was bugging out on me and apparently that did the trick.  Must have been purely coincidental that I did the league-of-legends upgrade at the same time.
