### ISSUE TITLE
r/leagueoflinux asked for you to reach out

### ISSUE THREAD

**Issue by StefanLobbenmeier** [kyechou/leagueoflegends#10]
https://reddit.com/r/leagueoflinux/comments/mv1pzp/start_here_league_of_linux_megathread_everything/

> leagueoflegends-git
>  • Install following the instructions on their Github page
> Editor's note: this method has come up a couple times in threads on this subreddit. I am not familiar with it so I cannot comment further on it. YMMV. If you are familiar with the project and can provide documentation or support, please reach out to me.

**Comment by kyechou** [comment]
Thank you Stefan! I've sent a message to see how I can help.
