### ISSUE TITLE
RiotClientServices Crash

### ISSUE THREAD

**Issue by Coolguy3289** [kyechou/leagueoflegends#105]
### System information

 - Distro: Arch
 - DE/WM/Compositor: KDE Plasma
 - CPU: AMD Ryzen 9 5900X 
 - GPU: AMD Radeon 6600XT
 - Graphics card drivers installed: amdgpu
 - 
### Describe the issue

When a fresh launch of the riot client happens (both during regular `leagueoflegends start` and `leagueoflegends install`, a wine crash notification is popping up stating "The Program RiotClientServices.exe has ancountered a serious problem and needs to close..." Below is the stack-trace:
http://haste.thegamingcorner.net/erelevybyx.mk

From the console: `wine: Unhandled page fault on read access to 00000006 at address 00464473 (thread 0640), starting debugger...`
### Steps to reproduce

After recent recompiliation of leagueoflegends-git from AUR;
1. run `leagueoflegends install`
2. Click "Install"
3. Once riot goes to launch see crash.

### Screenshots

![image](https://github.com/kyechou/leagueoflegends/assets/12205727/b8dac7e4-d8b4-48ba-8f25-d9c273e3dd07)

**Comment by Coolguy3289** [comment]
Note: If I simply close the error pop-up, it seems to continue with the launch, but when I get out of game, the client just crashes, I also notice the Riot task bar icon remains afterwards.

**Comment by kyechou** [comment]
Hi @Coolguy3289 , the issue about Riot task bar icon remaining is #99. There is an option in the Riot client's settings that can be turned on to exit the application instead of minimizing to system tray when it's closed.

The program error is very likely to be caused by incorrect vulkan driver being installed. Please double-check the vulkan driver supports the GPU used while launching the game.

**Comment by kyechou** [comment]
Hi @Coolguy3289 , I've updated the script to detect and abort when the correct vulkan driver files are not found. Please try again with the latest install and share the result. Thanks!

**Comment by Coolguy3289** [comment]
It worked without issue. There was also an update within the last few days to the amdgpu driver. I think part of the issue was I had installed the amf-amdgpu-pro driver which seems to utilize an older version of the amd driver.
