### ISSUE TITLE
locale doesn't work after the last update in AUR

### ISSUE THREAD

**Issue by Vintodrimmer** [kyechou/leagueoflegends#108]
### System information

 - Distro: Arch
 - DE/WM/Compositor: BSPWM
 - CPU: AMD 3900X
 - GPU: AMD 5700XT
 - Graphics card drivers installed: `mesa`, `vulkan-radeon`, `xf86-video-amdgpu`

### Describe the issue

I reinstalled wine and league after there was an update in AUR using `leagueoflegends reinstall`. Since then `--locale en_US` is ignored and I get Russian text in game and in game client. I tried the following so far:
1. Reinstalling with EUW server -> Riot client is in English, but the game itself and everything else is in Russian
2. Modifying the `LeagueClientSettings.yaml` -> it gets overwritten the next time I start the game
3. Making `LeagueClientSettings.yaml` immutable -> didn't help
4. Using both `region` and `locale` flags (`leagueoflegends --region ru_RU --locale en_US start`) -> no effect
5. Removing everything, deleting the `~/.local/share/leagueoflegends/` and reinstalling -> same result

### Steps to reproduce

1. Run `leagueoflegends install`
2. Login to an account that is tied to a Russian server and let it install/update
3. Restart with `leagueoflegends --locale en_US start`
4. See Russian language in client

**Comment by kyechou** [comment]
Hi @Vintodrimmer , please try again with the latest revision of the script. It should work now.

**Comment by Vintodrimmer** [comment]
Thanks a lot, works now!
