### ISSUE TITLE
13.14 seems to break something causing anticheat to trigger. 

### ISSUE THREAD

**Issue by Pouncingkitten** [kyechou/leagueoflegends#109]
I've had three accounts permabanned for cheating since 13.14 launched. I don't use other tools so it has to be Linux related. Consider adding a notice in the readme and perhaps other users can confirm whether this is widespread or not. 

Since the subreddit is dead I'm not sure where to look for other Linux users to confirm. Kbin is kind of dead.

**Comment by mikigal** [comment]
@ghost
Was your ban appeal accepted?

**Comment by mikigal** [comment]
@kyechou 
I sent ticket to Riot to confirm informations about bans for using your tool, conversation below (translated, I got response in language of my account). I also attached screenshot for proof. 
It looks that your great tool is totally safe for now and any eventual anti cheat false-positives bans will be cancelled.

Me: Hello, I wanted to install League of Legends on Arch Linux using Wine. Can I be banned for playing on Linux using Wine? Best regards, Mikołaj Gałązka

Me: I forgot to tell that I'm using official League of Legends client - I want to run it using Wine using simple script for automatically installing game client (https://aur.archlinux.org/packages/leagueoflegends-git). It does not modify anything in game's files

Riot (translated): Hello!

You can confidently write in Polish. If you want to play on Linux, nothing bad will happen, but please keep in mind that it is not officially supported by us, and we won't be able to provide technical support in case of any issues.

We also can't guarantee that more restrictive anti-cheat tools won't be introduced in the future, which could potentially conflict with such environments.

If you have any other questions or problems, feel free to reach out.
Player Support Specialist

<img width="1800" alt="riot" src="https://github.com/kyechou/leagueoflegends/assets/10632503/248190e0-bdef-4a88-9fd9-11f7dc742cf3">
