### ISSUE TITLE
No Cursor in Xwayland

### ISSUE THREAD

**Issue by Leaced** [kyechou/leagueoflegends#11]
Using the "leagueoflegends install" under wayland with sway as compositor opens a install window, but the install button can not be clicked, because there is no cursor.

I am not sure, if this is a problem of wine, xwayland, wine-lol, etc., but is there a way to install this game for me without needing a cursor in this step?

Could wine-wayland be a solution and how?
https://github.com/varmd/wine-wayland

**Comment by MarioGK** [comment]
Working on KDE Wayland session, maybe something only related to sway?

**Comment by Leaced** [comment]
yes. It is related to sway. Sway does not support the proprietary nvidia driver and nouveau does not support vulkan.
This issue can be closed.
