### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by HallerPatrick** [kyechou/leagueoflegends#114]
### System information

 - Distro: [Archcraft]
 - DE/WM/Compositor: [bspwm]
 - CPU: [AMD Ryzen 7 5800X]
 - GPU: [RTX 3060 Ti]
 - Graphics card drivers installed: [`nvidia`]

If your issue is related to graphics display, please attach the output of `vulkaninfo --summary`.

### Describe the issue
I followed the instruction to install league without any problem. After installing the game I closed it and restartet to log in. It does not matter if I input my valid user and password or random text I am always getting the error in the client "Sorry, we're having trouble signing you in right now. Please try again later."

I noticed following error messages in the logs:
1.
```
023c:err:winediag:getaddrinfo Failed to resolve your host name IP
0278:err:rpc:I_RpcGetBuffer no binding
```

2. 
```
011c:err:wininet:open_http_connection create_netconn failed: 12029
```

3. 
```
07bc:err:winstation:map_shared_memory_section failed to open section L"\\KernelObjects\\__wine_thread_mappings\\0000023c-input": c0000034
```

It seems that the client cannot properly communicate the the riot authentication server. But I am not sure how to resolve this.

**Comment by kyechou** [comment]
It looks like there's an issue with your DNS configuration. Please take a look at the documentation of your distribution for how to set up the DNS. For example, https://wiki.archlinux.org/title/Network_configuration and https://wiki.archlinux.org/title/Domain_name_resolution.
