### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by harshborana11** [kyechou/leagueoflegends#125]
:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 sane-1.2.1-5-x86_64 is up to date
 net-snmp-5.9.1-9-x86_64 is up to date
 lib32-mpg123-1.32.3-1-x86_64 is up to date
error: failed retrieving file 'lib32-mpg123-1.32.3-1-x86_64.pkg.tar.zst' from mirrors.nxtgen.com : The requested URL returned error: 404
error: failed retrieving file 'sane-1.2.1-5-x86_64.pkg.tar.zst' from mirrors.nxtgen.com : The requested URL returned error: 404
error: failed retrieving file 'net-snmp-5.9.1-9-x86_64.pkg.tar.zst' from mirrors.nxtgen.com : The requested URL returned error: 404
warning: too many errors from mirrors.nxtgen.com, skipping for the remainder of this transaction
error: failed retrieving file 'sane-1.2.1-5-x86_64.pkg.tar.zst' from mirror.sahil.world : The requested URL returned error: 404
error: failed retrieving file 'net-snmp-5.9.1-9-x86_64.pkg.tar.zst' from mirror.sahil.world : The requested URL returned error: 404
error: failed retrieving file 'sane-1.2.1-5-x86_64.pkg.tar.zst.sig' from in.mirrors.cicku.me : The requested URL returned error: 404
error: failed retrieving file 'net-snmp-5.9.1-9-x86_64.pkg.tar.zst.sig' from in.mirrors.cicku.me : The requested URL returned error: 404
error: failed retrieving file 'lib32-mpg123-1.32.3-1-x86_64.pkg.tar.zst.sig' from mirror.sahil.world : The requested URL returned error: 404
warning: too many errors from mirror.sahil.world, skipping for the remainder of this transaction
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.
 -> error installing repo packages
error installing repo packages
error installing repo packages

**Comment by kyechou** [comment]
Please take a look at the `-y` option in https://man.archlinux.org/man/pacman.8.en#SYNC_OPTIONS_(APPLY_TO_-S) and https://wiki.archlinux.org/title/Mirrors. The issue is not related to the LoL script. Thanks!

**Comment by harshborana11** [comment]
Ok sir sorry about that I'm new to linux terminal, I just used Ubuntu like for an year and half just as I used windows 😂
