### ISSUE TITLE
Vanguard patch coming soon, what are we gonna do?

### ISSUE THREAD

**Issue by goktug7913** [kyechou/leagueoflegends#126]
[Vanguard is going to become mandatory to play league](https://youtu.be/9U_jEzKf0_0?si=WGb498LjAUQBYRGZ&t=733) in the following weeks, and vanguard is a ring 0 windows kernel level anti-cheat.

So, probably we will have to either:

1. Somehow find a way to support it (practically impossible)
2. Wipe league of legends and all related files.

**Comment by Pierreluc14** [comment]
Vanguard will be on lol on 6 march 2024 if not delayed again to be confirmed on 14.4 patch notes on 21 february 2024.

**Comment by kyechou** [comment]
Thanks @goktug7913, sorry for the delayed reply!  It's getting more difficult for me to keep up with life recently.  Yes, I'm aware of the that.  For (1), I don't think that's possible with wine, and so one has to run Windows/MacOS one way or another if they want to play the game.  For (2), I plan to update README and archive the repository soon.

To cleanly uninstall league, simply run `leagueoflegends uninstall`. That will clean up everything.
