### ISSUE TITLE
Script broke with latest.

### ISSUE THREAD

**Issue by knarkzel** [kyechou/leagueoflegends#15]
- https://www.reddit.com/r/leagueoflinux/comments/pb4wqy/did_the_upgrade_to_cef91_as_part_of_1117_break/haarzou/?utm_source=share&utm_medium=web2x&context=3
- https://www.reddit.com/r/leagueoflinux/comments/pcqrc8/proof_of_concept_version_of_winelol_518/
- https://www.reddit.com/r/leagueoflinux/comments/pc5vao/new_lutris_installer_again/

Ran it on my machine using Arch Linux after `sudo pacman -Syyu`. After the first 2.9GB gets installed, I close the client and open with `leagueoflegends start`. After logging in, the client gets stuck at invalid attribute for some minutes, then crashes. Is there a way to fix this?

**Comment by kyechou** [comment]
Thank you @knarkzel! I've updated the README and the AUR package dependency requirements. It works fine now at my setup. Please reopen the issue if it still doesn't work.
