### ISSUE TITLE
Cant use mouse to move camera around

### ISSUE THREAD

**Issue by coreybruce** [kyechou/leagueoflegends#20]
Hi just want to report that you aren't able to use the mouse to freely move the camera around making the game unplayable unless you change the camera to follow you also the launcher is black unless you use DXVK, I would recommend having that installed by default.

Another thing I want to report is that the game takes quite a long time to launch and will sit there waiting for league of Legend client port to open

**Comment by ekistece** [comment]
yes, i have that bug also on gnome, maybe we could add a script that waits until the window is activated and activates and deactivates it...

**Comment by ekistece** [comment]
i added dxvk by default with my last PR

**Comment by coreybruce** [comment]
What can be done about the long time it takes to open the game launcher? should I start a post about that?

**Comment by ekistece** [comment]
Its the only current workaround to start league currently...

**Comment by coreybruce** [comment]
Oh Alright thanks for letting me know, hopefully more work in wine will fix it :)

**Comment by kyechou** [comment]
I've encountered the mouse issue a long time ago with either gnome or i3 (I forget now), which may be caused by how the WM handles the window, though wine should've captured the cursor. Which WM did you use?

**Comment by coreybruce** [comment]
> I've encountered the mouse issue a long time ago with either gnome or i3 (I can't remember now), which may be specific to the WM, though wine should've captured the cursor. Which WM/DE did you use?

I'm Using Gnome, a work around to it is to alt tab off than back onto the game to fix it

**Comment by Freggels** [comment]
not sure if that is related but running `leagueoflegends run winecfg` and enabling the virtual desktop fixed it for me on sway
