### ISSUE TITLE
Client not opening - Arch

### ISSUE THREAD

**Issue by Jralph4** [kyechou/leagueoflegends#26]
I installed league of legends with the helper script in the repositories. It's been working so far, I could play flawlessly. Yesterday I tried to open it as usual and it won't go. The initial loading window appears, and the riot icon appears as well in the bottom right corner. But when the loading screen is finished and the LoL logo should appear, it doesn't. and I'm left with the riot icon below.

This are the logs:

leagueoflegends -v start
+ shift
+ :
+ case "${1-}" in
+ break
+ case "${1-}" in
+ start_LoL
+ '[' '!' -f '/home/joa/.local/share/leagueoflegends/drive_c/Riot Games/Riot Client/RiotClientServices.exe' ']'
+ port_waiting_daemon
+ process=LeagueClientUx.exe
+ msg Starting...
+ loading_screen
+ echo -e '[+] Starting...'
[+] Starting...
+ wine '/home/joa/.local/share/leagueoflegends/drive_c/Riot Games/Riot Client/RiotClientServices.exe' --launch-product=league_of_legends --launch-patchline=live
+ '[' 1 -eq 1 ']'
+ zenity --progress --pulsate --auto-close --no-cancel '--title=League of Legends' --window-icon=/usr/share/icons/hicolor/256x256/apps/leagueoflegends.png '--text=Waiting for t
he League client port to open...'
++ timeout 2m sh -c 'until ps -C LeagueClientUx.exe -o pid=; do sleep 1; done | sed '\''s/[[:space:]]*//g'\'''
0034:err:module:__wine_process_init L"C:\\windows\\system32\\winemenubuilder.exe" not found
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
0080:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
022c:err:rpc:I_RpcGetBuffer no binding
+ uxpid=

**Comment by kyechou** [comment]
Hi @Jralph4, thanks for the issue! I just updated the script and AUR package source for a newer version of wine. It works on my setup with the latest patch (12.2). Please try again and reopen the issue if it persists!

**Comment by kyechou** [comment]
For anyone who found this thread, please install `leagueoflegends-ge-lol` instead of `leagueoflegends-git` if you have the same issue.
