### ISSUE TITLE
Black Screen Arch Linux

### ISSUE THREAD

**Issue by F1uk369** [kyechou/leagueoflegends#28]
!! Before creating an issue, please take a look at the [troubleshooting section](https://old.reddit.com/r/leagueoflinux/wiki/index#wiki_3_-_.1F527_tech_support_and_troubleshooting).

### System information

 - Distro: Arch Linux
 - DE/WM: Riced KDE
 - CPU: i5 10400 OC
 - GPU: 1660 super
 - Graphics card drivers installed: nvidia-dkms

If your issue is related to graphics display, please attach the output of `vulkaninfo`.

### Describe the issue

The screen is completely black when I open the game. It also says in wine that LeagueClientUxRenderer has crashed.

### Steps to reproduce

Verbose Output:
[+] Starting...
0894:err:winediag:gnutls_process_attach failed to load libgnutls, no support for encryption
0894:err:winediag:process_attach failed to load libgnutls, no support for pfx import/export
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support
0894:err:bcrypt:key_asymmetric_create no encryption support

(process:10864): Gtk-WARNING **: 21:57:10.811: Locale not supported by C library.
        Using the fallback 'C' locale.
09ec:err:rpc:I_RpcGetBuffer no binding
0a60:err:winediag:process_attach Failed to load libgnutls, secure connections will not be available.
0a60:err:secur32:SECUR32_initSchannelSP no schannel support, expect problems
0a60:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0a60:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0a60:err:winediag:gnutls_process_attach failed to load libgnutls, no support for encryption
0a60:err:winediag:process_attach failed to load libgnutls, no support for pfx import/export
ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pulse.so (libpulse.so.0: cannot open shared object file: No such file or directory)
ALSA lib dlmisc.c:337:(snd_dlobj_cache_get0) Cannot open shared library libasound_module_pcm_pulse.so (libpulse.so.0: cannot open shared object file: No such file or directory)
0b34:err:winediag:process_attach Failed to load libgnutls, secure connections will not be available.
0b34:err:secur32:SECUR32_initSchannelSP no schannel support, expect problems
0b34:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0b34:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0b34:err:winediag:gnutls_process_attach failed to load libgnutls, no support for encryption
0b34:err:winediag:process_attach failed to load libgnutls, no support for pfx import/export
0b34:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-1
0b34:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-1
0b78:err:winediag:process_attach Failed to load libgnutls, secure connections will not be available.
0b78:err:secur32:SECUR32_initSchannelSP no schannel support, expect problems
0b78:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0b78:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0b78:err:winediag:gnutls_process_attach failed to load libgnutls, no support for encryption
0b78:err:winediag:process_attach failed to load libgnutls, no support for pfx import/export
0b78:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-1
0b78:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-1
0b90:err:winediag:process_attach Failed to load libgnutls, secure connections will not be available.
0b90:err:secur32:SECUR32_initSchannelSP no schannel support, expect problems
0b90:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0b90:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0b90:err:winediag:gnutls_process_attach failed to load libgnutls, no support for encryption
0b90:err:winediag:process_attach failed to load libgnutls, no support for pfx import/export
0b90:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-1
0b90:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-1
0ba8:err:winediag:process_attach Failed to load libgnutls, secure connections will not be available.
0ba8:err:secur32:SECUR32_initSchannelSP no schannel support, expect problems
0ba8:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0ba8:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0ba8:err:winediag:gnutls_process_attach failed to load libgnutls, no support for encryption
0ba8:err:winediag:process_attach failed to load libgnutls, no support for pfx import/export
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
0bf8:err:winediag:process_attach Failed to load libgnutls, secure connections will not be available.
0bf8:err:secur32:SECUR32_initSchannelSP no schannel support, expect problems
0bf8:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0b08:err:bcrypt:key_asymmetric_create no encryption support
0bf8:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
0bf8:err:winediag:gnutls_process_attach failed to load libgnutls, no support for encryption
0bf8:err:winediag:process_attach failed to load libgnutls, no support for pfx import/export
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
0b08:err:bcrypt:key_asymmetric_create no encryption support
wine: Unhandled exception 0x80000003 in thread bf8 at address 126FE566 (thread 0bf8), starting debugger...
0780:err:winediag:process_attach Failed to load libgnutls, secure connections will not be available.
0780:err:secur32:SECUR32_initSchannelSP no schannel support, expect problems
0780:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0780:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0780:err:winediag:gnutls_process_attach failed to load libgnutls, no support for encryption
0780:err:winediag:process_attach failed to load libgnutls, no support for pfx import/export
0780:err:module:open_builtin_so_file failed to load .so lib "/usr/lib32/wine/i386-unix/d3d12.dll.so"
0780:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-1
0780:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-1

Wine Error Log:
0x126fe566 libcef+0x26fe566: int	$3
Modules:
Module	Address			Debug info	Name (74 modules)
PE	00350000-003aa000	Deferred        combase
PE	003b0000-003bd000	Deferred        userenv
PE	003c0000-003e9000	Deferred        winevulkan
PE	00400000-0081f000	Export          riotclientuxrender
PE	00820000-008e7000	Deferred        winmm
PE	008f0000-00af0000	Deferred        ffmpeg
PE	00af0000-00d1e000	Deferred        dxgi
PE	00d20000-00dc9000	Deferred        urlmon
PE	00dd0000-00df0000	Deferred        jsproxy
PE	01c20000-01cda000	Deferred        chrome_elf
PE	10000000-159c4000	Export          libcef
PE	61500000-6152f000	Deferred        iphlpapi
PE	61740000-61782000	Deferred        advapi32
PE	61940000-619cc000	Deferred        wininet
PE	61f40000-61f51000	Deferred        uiautomationcore
PE	62440000-62733000	Deferred        d3d9
PE	62b80000-62b88000	Deferred        api-ms-win-core-localization-l1-2-1
PE	62ec0000-62ece000	Deferred        ncrypt
PE	62fc0000-6304d000	Deferred        rpcrt4
PE	631c0000-631df000	Deferred        secur32
PE	63480000-6348c000	Deferred        version
PE	637c0000-63805000	Deferred        oleacc
PE	638c0000-638e7000	Deferred        credui
PE	63bc0000-63bda000	Deferred        shcore
PE	64a40000-64a94000	Deferred        shlwapi
PE	64ec0000-64fec000	Deferred        oleaut32
PE	65580000-6558d000	Deferred        wtsapi32
PE	65f40000-65f4c000	Deferred        kerberos
PE	66240000-66256000	Deferred        bcrypt
PE	663c0000-66472000	Deferred        winspool
PE	666c0000-666cf000	Deferred        hid
PE	66940000-66947000	Deferred        api-ms-win-security-systemfunctions-l1-1-0
PE	66b00000-66b3e000	Deferred        win32u
PE	66e40000-66e48000	Deferred        api-ms-win-appmodel-runtime-l1-1-2
PE	67800000-67807000	Deferred        api-ms-win-core-string-l1-1-0
PE	67840000-6784a000	Deferred        psapi
PE	67ec0000-687f8000	Deferred        shell32
PE	688c0000-688e9000	Deferred        netapi32
PE	69600000-69647000	Deferred        winhttp
PE	69940000-6996b000	Deferred        propsys
PE	69ac0000-69acc000	Deferred        vulkan-1
PE	6a040000-6a062000	Deferred        msacm32
PE	6a280000-6a32c000	Deferred        msvcrt
PE	6a400000-6a534000	Deferred        ole32
PE	6a540000-6a882000	Deferred        d3d11
PE	6aa40000-6aa48000	Deferred        usp10
PE	6ac80000-6ac87000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	6b500000-6b507000	Deferred        api-ms-win-core-localization-obsolete-l1-2-0
PE	6b9c0000-6b9cb000	Deferred        dhcpcsvc
PE	6bc00000-6bc2c000	Deferred        sechost
PE	6bcc0000-6bd3f000	Deferred        setupapi
PE	6be40000-6beba000	Deferred        dwrite
PE	6c740000-6c84b000	Deferred        cryptui
PE	6c9c0000-6ca46000	Deferred        gdi32
PE	6cc40000-6cd9c000	Deferred        comctl32
**Note:** Use the `-v` option and attach the verbose log outputs for all relevant commands. For long texts/logs, consider sharing them via services like [Gist](https://gist.github.com/). Do not attach screenshots for text/log outputs.

1. Go to '....'
3. Run command '....'
4. See error...
PE	6d780000-6d7a7000	Deferred        ws2_32
PE	6de80000-6de88000	Deferred        api-ms-win-core-synch-l1-2-0
PE	6e4c0000-6e4d6000	Deferred        dnsapi
PE	6e8c0000-6e995000	Deferred        crypt32
PE	6ec40000-6ec4d000	Deferred        dwmapi
PE	6ed00000-6ef3e000	Deferred        user32
PE	6f480000-6f48b000	Deferred        nsi
PE	6f4c0000-6f4e8000	Deferred        wintrust
PE	6fa80000-6fafa000	Deferred        dbghelp
PE	6ff80000-6ff87000	Deferred        api-ms-win-core-datetime-l1-1-1
PE	70940000-7095f000	Deferred        mpr
PE	70b40000-70c17000	Deferred        ucrtbase
PE	70d00000-70e08000	Deferred        comdlg32
PE	71200000-7121c000	Deferred        imm32
PE	712c0000-712e4000	Deferred        dxva2
PE	7b000000-7b0e9000	Deferred        kernelbase
PE	7b600000-7b81a000	Dwarf           kernel32
PE	7bc00000-7bca2000	Dwarf           ntdll
PE	7e1b0000-7e1b4000	Deferred        winex11
Threads:
process  tid      prio (all id:s are in hex)
00000038 services.exe
	0000003c    0
	00000040    0
	0000004c    0
	0000006c    0
	0000008c    0
	000000a4    0
	00000108    0
00000044 winedevice.exe
	00000048    0
	00000054    0
	00000058    0
	0000005c    0
	00000060    0
	000000b0    0
00000064 winedevice.exe
	00000068    0
	00000070    0
	00000074    0
	00000078    0
	0000007c    0
	00000080    0
00000084 plugplay.exe
	00000088    0
	00000090    0
	00000094    0
	00000098    0
	00000504    0
	0000039c    0
	00000434    0
0000009c svchost.exe
	000000a0    0
	000000a8    0
	000000ac    0
000000ec explorer.exe
	000000f0    0
	000000f4    0
	000000f8    0
00000100 rpcss.exe
	00000104    0
	00000110    0
	00000114    0
	00000118    0
	0000011c    0
	00000120    0
000007a0 RiotClientServices.exe
	000007a4    0
	000007b0    0
	000007b4    0
	000007b8    0
	000007bc    0
	000007c0    0
	000007c4    0
	000007d8    0
	00000808    0
	00000810    0
	00000814    0
	00000818    0
	0000081c    0
	00000034    0
	00000030    0
	0000002c    0
	00000028    0
	000000c0    0
	00000024    0
	000000b8    0
	000000bc    0
	00000020    0
	000000b4    0
	000000fc    0
	00000138    0
	0000013c    0
	00000168    0
	00000164    0
**Note:** Use the `-v` option and attach the verbose log outputs for all relevant commands. For long texts/logs, consider sharing them via services like [Gist](https://gist.github.com/). Do not attach screenshots for text/log outputs.

1. Go to '....'
3. Run command '....'
4. See error...
	00000170    0
	00000178    0
	0000016c    0
	00000180    0
	00000184    0
	00000050    0
	0000010c    0
	00000124    0
	000001e8    0
	000001ec    0
	000001f0    0
	000001f4    0
	000001f8    0
	000001fc    0
	00000200    0
	000001e0    0
	00000174    0
	000001dc    0
	0000023c    0
	00000240    0
	00000244    0
	00000248    0
	0000024c    0
	00000250    0
	00000258    0
	0000025c    0
	00000224    0
	00000204    0
	00000208    0
	0000020c    0
	00000210    0
	00000214    0
	00000218    0
	000001c8    0
	000001cc    0
	000001d0    0
	000001d4    0
	000001d8    0
	00000198    0
	0000019c    0
	00000188    0
	00000264    0
	00000550    0
	00000554    0
	0000054c    0
	000005e4    0
	000005d8    0
	000005d4    0
	000005e0    0
	00000578    0
	000005c8    0
	000005c0    0
	000005b8    0
	000005b0    0
	00000600    0
	000006b0    0
	00000694    0
	000006a4    0
	0000068c    0
	00000688    0
	000006a8    0
	000006ac    0
	00000604    0
	00000608    0
	0000060c    0
	00000610    0
	00000614    0
	00000618    0
	0000061c    0
	00000620    0
	00000624    0
	00000628    0
	0000062c    0
	00000630    0
	00000634    0
	00000638    0
	0000063c    0
	00000640    0
	00000644    0
000007a8 conhost.exe
	000007ac    0
000007dc RiotClientCrashHandler.exe
	000007e0    0
	000007ec    0
	000007f0    0
	000007f4    0
	000007f8    0
	000007fc    0
	00000800    0
	00000804    0
00000190 RiotClientUx.exe
	00000260    0
	00000298    0
	000002f0    0
	000002f4    0
	000002f8    0
	000002fc    0
	00000300   -2
	000002c4    0
	00000158    0
	00000148    0
	00000154    0
	00000150    0
	0000014c    0
	00000144    0
	00000140    0
	00000134    0
	00000160    0
	000000dc    0
	000000e8    0
	000000d0    0
	000000cc    0
	000002c0    0
	00000420   -2
	0000044c   -2
	00000430    0
	0000042c    0
	00000428    0
	00000648    0
	0000064c    0
	00000650    0
0000012c RiotClientCrashHandler.exe
	00000128    0
	000002cc    0
	000002d0    0
	000002d4    0
	000002c8    0
	000002e4    0
	000002e8    0
	000002ec    0
00000548 RiotClientUxRender.exe
	00000584    0
	000005a4    0
	000005ac    0
	000005b4    0
	000005c4    0
	000005cc    0
	00000590   -2
	00000594    0
	0000058c    0
	00000588    0
	000005dc    0
00000654 (D) C:\Riot Games\Riot Client\UX\RiotClientUxRender.exe
	00000658    0 <==
	0000065c    0
	0000067c    0
	00000678    0
	00000674    0
	000006b8    0
	00000500   -2
	000004d4    0
	000006bc    0
	000004d0    0
	000006c4    0
	000006c0    0
	000006e8    0
	000006e4    0
	000006e0    0
	00000700    0
	000006fc   -2
	00000704    0
	000006f4    0
	000006dc    0
	000006cc    0
	000006d4    0
	000006f0    0
	000006d8    0
	00000720    0
System information:
    Wine build: wine-7.0-rc5
    Platform: i386
    Version: Windows 7
    Host system: Linux
    Host version: 5.12.19-xanmod1-1

### Screenshots
Black. Also says waiting for League of Legends port to open but eventually closes.

**Comment by F1uk369** [comment]
Also attempting to install wine-ge-lol 7.0.GE.1.LoL-1 throws a few errors. When running yay wine-ge-lol it says error failed retrieving file 'sane-1.0.32-3-x86_64.pkg.tar.zst.sig'
warning: failed to retrieve some files
Errors occurred, no packages were upgraded.

**Comment by kyechou** [comment]
Hi @F1uk369, please first make sure your pacman mirror repositories are up to date (perhaps via tools like [reflector](https://wiki.archlinux.org/title/reflector)), and then run `pacman -Syy` before installing wine-ge-lol, or simply `yay -Syy wine-ge-lol`.

If the issue in the original post still remains after wine-ge-lol is installed, please provide the information as indicated in the issue template, including the output of `vulkaninfo`, `pacman -Qs wine`, `pacman -Qs nvidia`, `nvidia-smi`, etc.

**Comment by JPTIZ** [comment]
> Hi @F1uk369, please first make sure your pacman mirror repositories are up to date (perhaps via tools like [reflector](https://wiki.archlinux.org/title/reflector)), and then run `pacman -Syy` before installing wine-ge-lol, or simply `yay -Syy wine-ge-lol`.
> 
> If the issue in the original post still remains after wine-ge-lol is installed, please provide the information as indicated in the issue template, including the output of `vulkaninfo`, `pacman -Qs wine`, `pacman -Qs nvidia`, `nvidia-smi`, etc.


Not sure if it is the same issue, but I tested with a clean build after updating all my packages using `league-of-legends-ge-git` AUR package. Client opens nicely but the game itself freezes with no graphical updates and eventually the client recognizes I was idle for too much time and ends the game - although the game window is still open and frozen.

My `vulkaninfo`:
[vulkaninfo.txt](https://github.com/kyechou/leagueoflegends/files/7963932/vulkaninfo.txt)

**Comment by kyechou** [comment]
Hi @JPTIZ, I'm not sure if it's the same issue either, but it seems different. Please open up new a new issue. Thanks!

**Comment by kyechou** [comment]
@F1uk369 , if all is done and the issue remains, please try `leagueoflegends del-dxvk`

**Comment by kyechou** [comment]
Hi @F1uk369, I've updated README with some new information, and tested the game. Please take a look and try again with the leagueoflegends-git package. If the issue still remains, please consider attaching the information as mentioned above.

**Comment by F1uk369** [comment]
Wine now just says LeagueClientUX crashes.

Wine log:
0x126fe566 libcef+0x26fe566: int	$3
Modules:
Module	Address			Debug info	Name (74 modules)
PE	00350000-003aa000	Deferred        combase
PE	003b0000-003bd000	Deferred        userenv
PE	003c0000-003eb000	Deferred        winevulkan
PE	00400000-0081f000	Export          riotclientuxrender
PE	00820000-008e7000	Deferred        winmm
PE	008f0000-00af0000	Deferred        ffmpeg
PE	00af0000-00d1e000	Deferred        dxgi
PE	00d20000-00dc9000	Deferred        urlmon
PE	00dd0000-00df0000	Deferred        jsproxy
PE	01c20000-01cda000	Deferred        chrome_elf
PE	10000000-159c4000	Export          libcef
PE	61500000-6152f000	Deferred        iphlpapi
PE	61740000-61782000	Deferred        advapi32
PE	61940000-619cc000	Deferred        wininet
PE	61f40000-61f51000	Deferred        uiautomationcore
PE	62440000-62733000	Deferred        d3d9
PE	62b80000-62b88000	Deferred        api-ms-win-core-localization-l1-2-1
PE	62ec0000-62ece000	Deferred        ncrypt
PE	62fc0000-6304d000	Deferred        rpcrt4
PE	631c0000-631e0000	Deferred        secur32
PE	63480000-6348c000	Deferred        version
PE	637c0000-63805000	Deferred        oleacc
PE	638c0000-638e7000	Deferred        credui
PE	63bc0000-63bda000	Deferred        shcore
PE	64a40000-64a94000	Deferred        shlwapi
PE	64ec0000-64fec000	Deferred        oleaut32
PE	65580000-6558d000	Deferred        wtsapi32
PE	65f40000-65f4c000	Deferred        kerberos
PE	66240000-66256000	Deferred        bcrypt
PE	663c0000-66472000	Deferred        winspool
PE	666c0000-666cf000	Deferred        hid
PE	66940000-66947000	Deferred        api-ms-win-security-systemfunctions-l1-1-0
PE	66b00000-66b3e000	Deferred        win32u
PE	66e40000-66e48000	Deferred        api-ms-win-appmodel-runtime-l1-1-2
PE	67800000-67807000	Deferred        api-ms-win-core-string-l1-1-0
PE	67840000-6784a000	Deferred        psapi
PE	67ec0000-687f9000	Deferred        shell32
PE	688c0000-688e9000	Deferred        netapi32
PE	69600000-69648000	Deferred        winhttp
PE	69940000-6996b000	Deferred        propsys
PE	69ac0000-69acd000	Deferred        vulkan-1
PE	6a040000-6a062000	Deferred        msacm32
PE	6a280000-6a32c000	Deferred        msvcrt
PE	6a400000-6a534000	Deferred        ole32
PE	6a540000-6a882000	Deferred        d3d11
PE	6aa40000-6aa48000	Deferred        usp10
PE	6ac80000-6ac87000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	6b500000-6b507000	Deferred        api-ms-win-core-localization-obsolete-l1-2-0
PE	6b9c0000-6b9cb000	Deferred        dhcpcsvc
PE	6bc00000-6bc2c000	Deferred        sechost
PE	6bcc0000-6bd3f000	Deferred        setupapi
PE	6be40000-6beba000	Deferred        dwrite
PE	6c740000-6c84c000	Deferred        cryptui
PE	6c9c0000-6ca46000	Deferred        gdi32
PE	6cc40000-6cd9b000	Deferred        comctl32
PE	6d780000-6d7a7000	Deferred        ws2_32
PE	6de80000-6de88000	Deferred        api-ms-win-core-synch-l1-2-0
PE	6e4c0000-6e4d6000	Deferred        dnsapi
PE	6e8c0000-6e995000	Deferred        crypt32
PE	6ec40000-6ec4d000	Deferred        dwmapi
PE	6ed00000-6ef3e000	Deferred        user32
PE	6f480000-6f48b000	Deferred        nsi
PE	6f4c0000-6f4e8000	Deferred        wintrust
PE	6fa80000-6fafa000	Deferred        dbghelp
PE	6ff80000-6ff87000	Deferred        api-ms-win-core-datetime-l1-1-1
PE	70940000-7095f000	Deferred        mpr
PE	70b40000-70c17000	Deferred        ucrtbase
PE	70d00000-70e08000	Deferred        comdlg32
PE	71200000-7121c000	Deferred        imm32
PE	712c0000-712e4000	Deferred        dxva2
PE	7b000000-7b0e9000	Deferred        kernelbase
PE	7b600000-7b81a000	Dwarf           kernel32
PE	7bc00000-7bca2000	Dwarf           ntdll
PE	7dff0000-7dff4000	Deferred        winex11
Threads:
process  tid      prio (all id:s are in hex)
00000038 services.exe
	0000003c    0
	00000040    0
	0000004c    0
	0000006c    0
	0000008c    0
	000000a4    0
	00000108    0
00000044 winedevice.exe
	00000048    0
	00000054    0
	00000058    0
	0000005c    0
	00000060    0
	000000b0    0
00000064 winedevice.exe
	00000068    0
	00000070    0
	00000074    0
	00000078    0
	0000007c    0
	00000080    0
00000084 plugplay.exe
	00000088    0
	00000090    0
	00000094    0
	00000098    0
	00000500    0
	00000508    0
0000009c svchost.exe
	000000a0    0
	000000a8    0
	000000ac    0
000000ec explorer.exe
	000000f0    0
	000000f4    0
	000000f8    0
00000100 rpcss.exe
	00000104    0
	00000110    0
	00000114    0
	00000118    0
	0000011c    0
	00000120    0
0000026c RiotClientServices.exe
	00000270    0
	00000274    0
	00000278    0
	0000027c    0
	00000280    0
	00000284    0
	00000288    0
	0000028c    0
	00000290    0
000002a4 RiotClientServices.exe
	000002a8    0
	000002ac    0
	000002b0    0
	000002b4    0
	000002b8    0
	000002bc    0
	000002c0    0
	00000308    0
	00000330    0
	00000334    0
	00000338    0
	0000033c    0
	00000340    0
	00000344    0
	00000348    0
	0000034c    0
	00000350    0
	00000354    0
	00000358    0
	0000035c    0
	00000360    0
	00000364    0
	00000368    0
	0000036c    0
	00000370    0
	00000374    0
	00000378    0
	0000037c    0
	00000380    0
	00000384    0
	00000388    0
	0000038c    0
	00000390    0
	00000394    0
	00000398    0
	0000039c    0
	000003a4    0
	000003a8    0
	000003ac    0
	000003b0    0
	000003b4    0
	000003b8    0
	000003bc    0
	000003c0    0
	000003c4    0
	000003c8    0
	000003cc    0
	000003d0    0
	000003d4    0
	000003d8    0
	000003dc    0
	000003e0    0
	000003e4    0
	000003e8    0
	000003ec    0
	000003f0    0
	000003f4    0
	000003f8    0
	000003fc    0
	00000400    0
	00000404    0
	00000408    0
	0000040c    0
	00000410    0
	00000414    0
	00000418    0
	0000041c    0
	00000420    0
	00000458    0
	0000045c    0
	00000560    0
0000030c RiotClientCrashHandler.exe
	00000310    0
	00000314    0
	00000318    0
	0000031c    0
	00000320    0
	00000324    0
	00000328    0
	0000032c    0
00000440 RiotClientUx.exe
	00000444    0
	00000464    0
	0000048c    0
	00000490    0
	00000494    0
	00000498    0
	0000049c   -2
	000004a0    0
	000004c0    0
	000004c4    0
	000004c8    0
	000004cc    0
	000004d0    0
	000004d4    0
	000004d8    0
	000004dc    0
	000004e0    0
	000004e4    0
	000004e8    0
	000004f4    0
	000004f8    0
	000004fc    0
	00000504   -2
	0000050c   -2
	00000510    0
	00000518    0
	0000051c    0
	00000630    0
	00000634    0
	00000638    0
00000468 RiotClientCrashHandler.exe
	0000046c    0
	00000470    0
	00000474    0
	00000478    0
	0000047c    0
	00000480    0
	00000484    0
	00000488    0
00000564 RiotClientUxRender.exe
	00000568    0
	0000057c    0
	00000580    0
	00000584    0
	0000058c    0
	00000590    0
	00000594   -2
	00000598    0
	0000059c    0
	000005a0    0
	000005a4    0
0000063c (D) C:\Riot Games\Riot Client\UX\RiotClientUxRender.exe
	00000640    0 <==
	00000644    0
	00000648    0
	0000064c    0
	00000650    0
	00000654    0
	00000658   -2
	0000065c    0
	00000660    0
	00000664    0
	00000668    0
	0000066c    0
	00000670    0
	00000674    0
	00000678    0
	0000067c    0
	00000680   -2
	00000684    0
	00000688    0
	0000068c    0
	00000690    0
	00000694    0
	00000698    0
	0000069c    0
	000006a8    0
System information:
    Wine build: wine-7.1
    Platform: i386
    Version: Windows 7
    Host system: Linux
    Host version: 5.15.22-xanmod1-1


Vulkaninfo:
ERROR: [Loader Message] Code 0 : loader_scanned_icd_add: Driver /usr/lib/amdvlk64.so says it supports interface version 6 but still exports core entrypoints (Policy #LDP_DRIVER_6)
ERROR: [Loader Message] Code 0 : loader_scanned_icd_add: Driver /usr/lib/libvulkan_intel.so supports Vulkan 1.2, but only supports loader interface version 4. Interface version 5 or newer required to support this version of Vulkan (Policy #LDP_DRIVER_7)
ERROR at /build/vulkan-tools/src/Vulkan-Tools-1.2.203/vulkaninfo/vulkaninfo.h:672:vkCreateInstance failed with ERROR_OUT_OF_HOST_MEMORY

pacman -Qs wine:
local/dxvk-bin 1.9.4-2
    A Vulkan-based compatibility layer for Direct3D 9/10/11 which allows running 3D applications on Linux using Wine (Windows DLL binary files)
local/wine 7.1-1
    A compatibility layer for running Windows programs
local/wine-ge-lol 7.0.GE.1.LoL-3
    A compatibility layer for running League of Legends - GloriousEggroll branch
local/wine-gecko 2.47.2-3
    Wine's built-in replacement for Microsoft's Internet Explorer
local/wine-mono 7.0.0-2
    Wine's built-in replacement for Microsoft's .NET Framework
local/winetricks 20210825-1
    Script to install various redistributable runtime libraries in Wine.

pacman -Qs nvidia:
local/egl-wayland 2:1.1.9+r3+g582b2d3-1
    EGLStream-based Wayland external platform
local/lib32-nvidia-utils 510.47.03-1
    NVIDIA drivers utilities (32-bit)
local/libvdpau 1.4-1
    Nvidia VDPAU library
local/libxnvctrl 510.47.03-1
    NVIDIA NV-CONTROL X extension
local/nvidia 510.47.03-4
    NVIDIA drivers for linux
local/nvidia-dkms 510.47.03-3
    NVIDIA drivers - module sources
local/nvidia-settings 510.47.03-1
    Tool for configuring the NVIDIA graphics driver
local/nvidia-utils 510.47.03-3
    NVIDIA drivers utilities
local/xf86-video-nouveau 1.0.17-2 (xorg-drivers)
    Open Source 3D acceleration driver for nVidia cards


NVIDIA-SMI:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| 30%   46C    P0    38W / 125W |    778MiB /  6144MiB |     24%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       580      G   /usr/lib/Xorg                     314MiB |
|    0   N/A  N/A       847      G   /usr/bin/kwin_x11                 124MiB |
|    0   N/A  N/A       864      G   /usr/bin/plasmashell              215MiB |
|    0   N/A  N/A       921      G   /usr/bin/latte-dock                32MiB |
|    0   N/A  N/A      4500      G   /usr/bin/ark                        2MiB |
|    0   N/A  N/A    165553      G   ...670849020105473118,131072       82MiB |
+-----------------------------------------------------------------------------+
