### ISSUE TITLE
How to sign into Riot account with Google

### ISSUE THREAD

**Issue by DgDays** [kyechou/leagueoflegends#30]
All progress is saved in an account linked to Google. Can I somehow enter the game through it?

**Comment by kyechou** [comment]
I don't know, and the issue doesn't seem to be particular to LoL on Linux.

**Comment by DgDays** [comment]
Unfortunately, the problem is in the client... The site tries to find the application using the riotclient://auth/v1/token link, but does not find the client... You need to somehow bind riotclient:// to the program and, I think, then all the necessary data will be transferred by itself
Based on the principle of data transfer, we need the client to create a server to which this link will go, because riotclient:// looks a lot like http:// 🤔
It remains only to find a way to implement this idea and test

PS Sorry if it's very hard to read. I don't know English well, so I communicate through an interpreter

**Comment by kyechou** [comment]
Hi @DgDays, I'm think I understand your general idea, but I'm not sure how their internals work and also don't have the resources to figure out how to implement that for the time being. Another potential workaround might be to sign in at https://account.riotgames.com first. You should be able to sign in through Google there. And then you may be able to set up the password and manage the connected social accounts in that page. Afterwards, you may sign in with the username and password credentials in the client. I haven't really tried it myself. Please let me know if that works or not. Thanks!

**Comment by DgDays** [comment]
Yes, it worked. But, I think, we should still try to set up registrations. If I come up with something or find out, I'll write it here ;)

**Comment by kyechou** [comment]
Closing for now. Please feel free to send in pull requests as well :)
