### ISSUE TITLE
Client opens and works as expected, but game screen is frozen

### ISSUE THREAD

**Issue by JPTIZ** [kyechou/leagueoflegends#31]
!! Before creating an issue, please take a look at the [troubleshooting section](https://old.reddit.com/r/leagueoflinux/wiki/index#wiki_3_-_.1F527_tech_support_and_troubleshooting).

### System information

 - Distro: ArchLinux (5.16.2.arch1-1)
 - DE/WM: i3
 - CPU: Intel(R) Core(TM) i5-7300HQ
 - GPU: GeForce GTX 1050 Mobile
 - Graphics card drivers installed: `nvidia` (`mesa` is installed, but just for when I'm not running i3 with `nvidia-xrun` - which is not the case of this issue)

If your issue is related to graphics display, please attach the output of `vulkaninfo`.
**vulkaninfo output**: [vulkaninfo.txt](https://github.com/kyechou/leagueoflegends/files/7964030/vulkaninfo.txt)

### Describe the issue

League of Legends's Client opens and works as expected, but the game itself freezes with no graphical updates and eventually the client recognizes I was idle for too much time and ends the game - although the game window is still open and frozen.

### Steps to reproduce

In a clean install (in Arch, installing `leagueoflegends-ge-git` followed by running `leagueoflegends install`):
- Run `leagueoflegends start`;
- Once client opens (after login and updates), start any match. In this example, a Training Match on Training Mode;
- After character selection, game window will open, but without any graphical updates just as if drawing commands were never issued like when a game freezes (on i3, this means you'll be seeing your wallpaper, or any graphic memory buffer garbage if you try to switch between fullscreen/windowed mode);
- After a while, the client will recognize you're idle ingame (somehow) and take you back to the client screen.
- Game screen will still be there, still without graphical updates. Trying to initialize another game causes crashes on game (but not on client).

Additioanl info: `leagueoflegends --verbose start` log:

```console
$ leagueoflegends --verbose start
+ shift
+ :
+ case "${1-}" in
+ break
+ case "${1-}" in
+ start_LoL
+ '[' '!' -f '/home/jptiz/.local/share/leagueoflegends/drive_c/Riot Games/Riot Client/RiotClientServices.exe' ']'
+ port_waiting_daemon
+ msg Starting...
+ echo -e '[+] Starting...'
+ process=LeagueClientUx.exe
[+] Starting...
+ loading_screen
+ '[' 1 -eq 1 ']'
+ zenity --progress --pulsate --auto-close --no-cancel '--title=League of Legends' --window-icon=/usr/share/icons/hicolor/256x256/apps/leagueoflegends.png '--text=Waiting for the League client port to open...'
++ timeout 2m sh -c 'until ps -C LeagueClientUx.exe -o pid=; do sleep 1; done | sed '\''s/[[:space:]]*//g'\'''
++ winepath -w '/home/jptiz/.local/share/leagueoflegends/drive_c/Riot Games/Riot Client/RiotClientServices.exe'
wineserver: using server-side synchronization.
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
+ wine 'C:\Riot Games\Riot Client\RiotClientServices.exe' --launch-product=league_of_legends --launch-patchline=live
021c:err:rpc:I_RpcGetBuffer no binding
+ uxpid=173613
+ '[' -z 173613 ']'
++ xargs -0
++ sed -n 's/.*--app-port=\([[:digit:]]*\).*/\1/p'
+ port=37065
+ '[' -z 37065 ']'
+ kill -STOP 173613
+ timeout 5m bash -c '
    until openssl s_client -connect :37065 <<< Q >/dev/null 2>&1; do
        sleep 1
    done'
+ kill -CONT 173613
0628:err:vulkan:X11DRV_vkCreateWin32SurfaceKHR Failed to allocate client window for hwnd=0x100f2
```

### Screenshots

![image](https://user-images.githubusercontent.com/11988816/151668498-2a76589e-4c5a-4476-9032-b30336f88af9.png)

A small demonstration that when game opens and freezes, mouse will disappear when you hover it (which is expected), meaning the window is indeed opened:

https://user-images.githubusercontent.com/11988816/151668536-d0da46d5-a137-4025-8300-7fd5ddbae5d1.mp4

**Comment by kyechou** [comment]
Hi @JPTIZ, thanks for the issue. The logs seem fine. Would you mind trying `leagueoflegends del-dxvk` first, and then starting the game? Also, it might be helpful too if you could share the output of `pacman -Qi leagueoflegends-ge-git`.

**Comment by JPTIZ** [comment]
> Hi @JPTIZ, thanks for the issue. The logs seem fine. Would you mind trying `leagueoflegends del-dxvk` first, and then starting the game? Also, it might be helpful too if you could share the output of `pacman -Qi leagueoflegends-ge-git`.

Here it goes the last part:

```console
$ pikaur -Qi leagueoflegends-ge-git
Name            : leagueoflegends-ge-git
Version         : 0.12.2.r6.gb03da00-1
Description     : League of Legends helper script
Architecture    : any
URL             : https://github.com/kyechou/leagueoflegends
Licenses        : GPL3
Groups          : None
Provides        : leagueoflegends
Depends On      : winetricks-git  bash  curl  openssl  samba  lib32-gnutls  lib32-libldap  lib32-openal  lib32-libpulse
                  lib32-alsa-lib  lib32-unixodbc  lib32-vkd3d  vulkan-icd-loader  lib32-vulkan-icd-loader
                  vulkan-driver  lib32-vulkan-driver  wine-ge-lol
Optional Deps   : lib32-amdvlk: AMD Vulkan driver
                  lib32-nvidia-utils: NVIDIA Vulkan driver [installed]
                  lib32-vulkan-intel: Intel's Vulkan mesa driver [installed]
                  lib32-vulkan-radeon: Radeon's Vulkan mesa driver
                  zenity: Loading screen indication [installed]
Required By     : None
Optional For    : None
Conflicts With  : leagueoflegends  leagueoflegends-git
Replaces        : leagueoflegends-git
Installed Size  : 132.12 KiB
Packager        : Unknown Packager
Build Date      : Sat Jan 29 00:55:06 2022
Install Date    : Sat Jan 29 00:55:20 2022
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```
I'll test the del-dxvk one.

**Comment by JPTIZ** [comment]
Ok, with `leagueoflegends del-dxvk`, the game opens and I can play! :D Only drawback now tho is that the client is fully black so I had to figure out by memory where each option was to enter a training match to test :) So selecting runes/etc. is a no-no.

**Comment by kyechou** [comment]
Well, that's progress :smile: but the blank client is definitely not good. I haven't encountered this problem before, but I guess it might have something to do with using multiple GPUs (integrated and dedicated)? I wonder if it's possible to remove `lib32-vulkan-intel`. Is it needed by other packages? Perhaps try again after removing `lib32-vulkan-intel`? Also, is there a way to check that all those processes are using the nvidia card? (like `nvidia-smi`?)

**Comment by kyechou** [comment]
May be related: https://www.reddit.com/r/leagueoflinux/comments/r0oo0p/i_got_league_working_again_on_my_nvidia_drivers/

**Comment by kyechou** [comment]
Hi @JPTIZ, according to the [previous link](https://www.reddit.com/r/leagueoflinux/comments/r0oo0p/i_got_league_working_again_on_my_nvidia_drivers/), I used https://github.com/Frogging-Family/nvidia-all to downgrade my nvidia packages to 470.94-195, and reinstalled leagueoflegends-git with wine-lol and wine-lol-glibc. No need to set the DX9 legacy mode in the League client. The game runs perfectly well on my setup. Please give it a try!

**Comment by JPTIZ** [comment]
> Hi @JPTIZ, according to the [previous link](https://www.reddit.com/r/leagueoflinux/comments/r0oo0p/i_got_league_working_again_on_my_nvidia_drivers/), I used https://github.com/Frogging-Family/nvidia-all to downgrade my nvidia packages to 470.94-195, and reinstalled leagueoflegends-git with wine-lol and wine-lol-glibc, and dxvk is enabled by default for a fresh setup. No need to set the DX9 legacy mode in the League client. The game runs perfectly well on my setup. Please give it a try!

Tried it but I have an internal problem with nvidia in this case, as I get "no screen found" errors with older `nvidia` versions when running `nvidia-xrun`. Probably will have to wait for another update in my case.

> _Edit_ According to that post, reinstalling the latest nvidia packages and clearing up all caches should also work, but I haven't tried it.

I could try it. Which caches exactly?

> _Edit_ I've also updated README. Hope that's helpful.

Took a quick look, nice pointings :)

**Comment by kyechou** [comment]
> I could try it. Which caches exactly?

Anything related to the graphics card and X11 I assume. They have the detailed process of how to do exactly that in the [original post](https://www.reddit.com/r/leagueoflinux/comments/r0oo0p/i_got_league_working_again_on_my_nvidia_drivers/).

**Comment by kyechou** [comment]
@JPTIZ, I've updated README some time ago thanks to #34 and [u/112138](https://www.reddit.com/user/112138/). Please check out the troubleshooting section at the end of README, and let me know if there's still an issue. Thanks!

**Comment by JPTIZ** [comment]
Tried some of the things (looked for dxvk files, but none found - yet I ran `leagueoflegends rm-dxvk-cache`) but no success.

Also, I find it rather strange that output shows MESA-INTEL warnings:

```
 $ leagueoflegends start                                                                                                                                                                            [+] Starting...
wineserver: using server-side synchronization.
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
```

does it mean it might be trying to use mesa driver instead of nvidia? How could I force nvidia to be used (I even start X with `nvidia-xrun i3`, so NVidia GPU is the 3D accelerator, so it wouldn't make sense that it tried to use the integrated Intel card)? Trying to uninstall mesa give me errors because it is a dependency of other packages (which I find peculiar, thought it should be interchangeable with `nvidia` driver, but may make sense for the integrated graphics):

```
$ pikaur -R mesa                                                                                                                                                                                   checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: removing mesa breaks dependency 'mesa' required by cogl
:: removing mesa breaks dependency 'mesa' required by gst-plugins-base-libs
:: removing mesa breaks dependency 'mesa' required by gtk3
:: removing mesa breaks dependency 'mesa' required by lib32-mesa
:: removing mesa breaks dependency 'mesa' required by libglvnd
:: removing mesa breaks dependency 'mesa' required by mpv
:: removing mesa breaks dependency 'mesa' required by nvidia-xrun-git
:: removing mesa breaks dependency 'mesa' required by qt5-base
:: removing mesa breaks dependency 'mesa' required by qt6-base
:: removing mesa breaks dependency 'mesa' required by retroarch
:: removing mesa breaks dependency 'mesa' required by slop
```

**Comment by JPTIZ** [comment]
UPDATE! After all that DXVK cache mess, I tried `leagueoflegends add-dxvk` and client shows as expected! :D

**Comment by kyechou** [comment]
@JPTIZ , I don't think you need to remove mesa. In your previous comment, I saw you have both `lib32-nvidia-utils` and `lib32-vulkan-intel` installed. That might be an issue. Please check the output of `vulkaninfo --summary`, and remove `lib32-vulkan-intel` assuming you're using the Nvidia card.

**Comment by JPTIZ** [comment]
> 

Oh, in the end the `add-dxvk` managed to make it work :) I've messed before with `del-dxvk` (as recommended [here](https://github.com/kyechou/leagueoflegends/issues/31#issuecomment-1025002043)) and etc. and never readded it.

Currently, LoL has been working fine on my computer, fully playable.

**Comment by kyechou** [comment]
Congrats!
