### ISSUE TITLE
Cannot open client

### ISSUE THREAD

**Issue by floorcows** [kyechou/leagueoflegends#32]
!! Before creating an issue, please take a look at the [troubleshooting section](https://old.reddit.com/r/leagueoflinux/wiki/index#wiki_3_-_.1F527_tech_support_and_troubleshooting).

### System information

 - Distro: Arch
 - DE/WM: i3
 - CPU: Intel i7-7700HQ (8) @ 3.800GHz
 - GPU: NVIDIA GeForce GTX 1050 Ti Mobile 
 - Graphics card drivers installed: nvidia mesa and integrated

### Describe the issue

Hello.
I am having issues starting the client. My issue is similar to #26.

### Steps to reproduce

1. Install leagueoflegends-ge-git
2. leagueoflegends -v install
3. close the window
3. leagueoflegends -v start
4. The launcher opens. There is an update. After the update is done, logging in will display the league logo then do nothing. Here is my terminal output:

+ shift
+ :
+ case "${1-}" in
+ break
+ case "${1-}" in
+ start_LoL
+ '[' '!' -f '/home/cri/.local/share/leagueoflegends/drive_c/Riot Games/Riot Client/RiotClientServices.exe' ']'
+ port_waiting_daemon
+ msg Starting...
+ process=LeagueClientUx.exe
+ echo -e '[+] Starting...'
[+] Starting...
+ loading_screen
+ '[' 1 -eq 1 ']'
+ zenity --progress --pulsate --auto-close --no-cancel '--title=League of Legends' --window-icon=/usr/share/icons/hicolor/256x256/apps/leagueoflegends.png '--text=Waiting for the League client port to open...'
++ timeout 2m sh -c 'until ps -C LeagueClientUx.exe -o pid=; do sleep 1; done | sed '\''s/[[:space:]]*//g'\'''
++ winepath -w '/home/cri/.local/share/leagueoflegends/drive_c/Riot Games/Riot Client/RiotClientServices.exe'
wineserver: using server-side synchronization.
+ uxpid=205461
+ '[' -z 205461 ']'
++ xargs -0
++ sed -n 's/.*--app-port=\([[:digit:]]*\).*/\1/p'
+ port=43329
+ '[' -z 43329 ']'
+ kill -STOP 205461
+ timeout 5m bash -c '
    until openssl s_client -connect :43329 <<< Q >/dev/null 2>&1; do
        sleep 1
    done'
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2).
+ wine 'C:\Riot Games\Riot Client\RiotClientServices.exe' --launch-product=league_of_legends --launch-patchline=live
0230:err:rpc:I_RpcGetBuffer no binding
036c:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-1
036c:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-1
03b4:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-1
03b4:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-1
03cc:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-1
03cc:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-1
0594:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-1
0594:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-1
0594:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-1
0594:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-1
06e8:err:vulkan:wine_vkCreateInstance Failed to create instance, res=-1
+ wineserver --wait

**Comment by kyechou** [comment]
That's very likely due to vulkan and issues with the graphics packages, maybe similar to #16. Could you please try https://wiki.archlinux.org/title/Vulkan#Verification, and also share the output of `pacman -Qi leagueoflegends-ge-git`, `pacman -Qs nvidia`, and `pacman -Qs vulkan`?

**Comment by kyechou** [comment]
Hi @floorcows, I just tested the game with both packages, and they should both work fine. I updated README with some more information. Please take a look and share the output as mentioned above. Thanks!

**Comment by floorcows** [comment]
Hello, Thank you for the support!
I always launch the game in optimus-manager's nvidia mode.
Here are the outputs:
## ls /usr/share/vulkan/icd.d/:
amc_idc32.json nvidia_icd.json
## vulkaninfo:
[vulkaninfo.txt](https://github.com/kyechou/leagueoflegends/files/7972654/vulkaninfo.txt)
## leagueoflegends-ge-git
`Name            : leagueoflegends-ge-git
Version         : 0.12.2.r7.gd509cd6-1
Description     : League of Legends helper script
Architecture    : any
URL             : https://github.com/kyechou/leagueoflegends
Licenses        : GPL3
Groups          : None
Provides        : leagueoflegends
Depends On      : winetricks-git  bash  curl  openssl  samba  lib32-gnutls  lib32-libldap  lib32-openal  lib32-libpulse  lib32-alsa-lib  lib32-unixodbc
                  lib32-vkd3d  vulkan-icd-loader  lib32-vulkan-icd-loader  vulkan-driver  lib32-vulkan-driver  wine-ge-lol
Optional Deps   : lib32-amdvlk: AMD Vulkan driver [installed]
                  lib32-nvidia-utils: NVIDIA Vulkan driver [installed]
                  lib32-vulkan-intel: Intel's Vulkan mesa driver
                  lib32-vulkan-radeon: Radeon's Vulkan mesa driver
                  zenity: Loading screen indication [installed]
Required By     : None
Optional For    : None
Conflicts With  : leagueoflegends  leagueoflegends-git
Replaces        : leagueoflegends-git
Installed Size  : 132.10 KiB
Packager        : Unknown Packager
Build Date      : Mon 31 Jan 2022 03:50:17 AM CET
Install Date    : Mon 31 Jan 2022 05:27:43 AM CET
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None`
## nvidia:
`local/egl-wayland 2:1.1.9+r3+g582b2d3-1
    EGLStream-based Wayland external platform
local/lib32-nvidia-utils 495.46-1
    NVIDIA drivers utilities (32-bit)
local/libvdpau 1.4-1
    Nvidia VDPAU library
local/libxnvctrl 495.46-2
    NVIDIA NV-CONTROL X extension
local/nvidia 495.46-12
    NVIDIA drivers for linux
local/nvidia-dkms 495.46-2
    NVIDIA drivers - module sources
local/nvidia-settings 495.46-2
    Tool for configuring the NVIDIA graphics driver
local/nvidia-utils 495.46-2
    NVIDIA drivers utilities
local/nvtop 1.2.2-1
    An htop like monitoring tool for NVIDIA GPUs`
# vulkan
`local/lib32-amdvlk 2022.Q1.2-1
    AMD's standalone Vulkan driver
local/lib32-nvidia-utils 495.46-1
    NVIDIA drivers utilities (32-bit)
local/lib32-vkd3d 1.2-2
    Direct3D 12 to Vulkan translation library By WineHQ
local/lib32-vulkan-icd-loader 1.2.203-1
    Vulkan Installable Client Driver (ICD) Loader (32-bit)
local/nvidia-utils 495.46-2
    NVIDIA drivers utilities
local/spirv-tools 2021.4-1 (vulkan-devel)
    API and commands for processing SPIR-V modules
local/vkd3d 1.2-1
    Direct3D 12 to Vulkan translation library By WineHQ
local/vulkan-headers 1:1.3.204-1 (vulkan-devel)
    Vulkan header files
local/vulkan-icd-loader 1.2.203-1
    Vulkan Installable Client Driver (ICD) Loader
local/vulkan-tools 1.2.203-1 (vulkan-devel)
    Vulkan Utilities and Tools`

**Comment by kyechou** [comment]
Hi @floorcows, yeah I saw there are `lib32-amdvlk` and `lib32-nvidia-utils` both installed. Since you're using Nvidia, you should probably remove `lib32-amdvlk`. Ideally that should solve the problem

**Comment by kyechou** [comment]
It seems to be the same issue as #24.

**Comment by floorcows** [comment]
Removing lib32-amdvlk fixed the issue, i am now able to launch the client. Thanks. 
It is now the game itself that blackscreens, I will follow the steps [here](https://old.reddit.com/r/leagueoflinux/comments/r0oo0p/i_got_league_working_again_on_my_nvidia_drivers/).

**Comment by kyechou** [comment]
Great! Please also take a look at #31.
