### ISSUE TITLE
Doesn't work on Debian?

### ISSUE THREAD

**Issue by inezserrano** [kyechou/leagueoflegends#36]
dpkg: error: cannot access archive 'leagueoflegends.deb': No such file or directory

I have no idea where I'm supposed to get this.

**Comment by kyechou** [comment]
Thanks for the issue. I just updated README and hopefully it's a bit more clear. You need to specify the deb package that you generated with `./package.sh debian`. It looks something like `leagueoflegends_0.12.3_any.deb`.
