### ISSUE TITLE
Runes do not save

### ISSUE THREAD

**Issue by caseyjp11** [kyechou/leagueoflegends#38]
### System information

 - Distro:  Arch
 - DE/WM: KDE
 - CPU: AMD FX6 series
 - GPU: AMD RX550 (lexa pro)
 - Graphics card drivers installed: AMD drivers-non proprietary

The game itself works fine as far as I can tell. FPS and client responsiveness is spot on.

The problem I'm having is creating custom runes. I create a new set, select what I want, label it, save it, and in-game it works. UNTIL...I exit the game. When I restart, the custom rune sets are just...gone. As if they've never been. Is this just me? I'm not seeing any errors other than this when the session changes from one window to another throwing this error:

04e8:err:vulkan:X11DRV_vkCreateWin32SurfaceKHR Failed to allocate client window for hwnd=0x10
0d4
(I don't believe this has a thing to do with Runes not saving, but it does pop up in the command prompt where I'm running the script. It isn't a crasher as the windows and sessions work just fine while in-game.)

A clear and concise description of what the issue is:

Rune saves don't work from one gaming session to the next. I used the -v option and the vulkan error is as shown above.

### Screenshots

I'd toss in a shot, but during a session, the custom runes save, can be edited and used in a match.
Exit the client and come back, and all the custom work is gone.

I've reported this in the /reddit forum and another user is reporting the same issue with this comment:

[AndrewTheNoob_](https://www.reddit.com/user/AndrewTheNoob_/)
Yep same issue here. I tried to actually save the runes from a post exit script then load it again in the launchhelper.sh, but it seems like runes pages are actually resetting during the launch of the client.
The file that saves runes (and also summoner spells) is located at /drive_c/Riot Games/League of Legends/Config/PerksPreferences.yaml

**Comment by kyechou** [comment]
Thanks for reporting the issue! Though unfortunately I won't have time recently to look into the problem or test it. So any help would be appreciated!

**Comment by caseyjp11** [comment]
A bit more info. This might NOT be an issue with Wine or the script. In the LoL subreddit, there are reports that this is happening with the native client as well.
I'm wondering if most players don't use/know how to change the default selections and thus hasn't gotten as much attention as it probably should be getting from RIOT.
If I see a resolution, I'll toss it here, but for the moment this IS a bug...but it might be an upstream issue with the client itself rather than the script.

**Comment by kyechou** [comment]
Thanks for letting me know @caseyjp11. Just to record some updates for future references:
* [The r/leagueoflinux thread](https://www.reddit.com/r/leagueoflinux/comments/t5gpc6/custom_runes_wont_save/)
* [(one of many) r/leagueoflegends threads](https://www.reddit.com/r/leagueoflegends/comments/soyl6p/runes_reset_when_logging_out_of_league/), other threads: [1](https://www.reddit.com/r/leagueoflegends/comments/sq59zd/runes_disappearing/), [2](https://www.reddit.com/r/leagueoflegends/comments/styelx/problem_with_runes/), [3](https://www.reddit.com/r/leagueoflegends/comments/stn1ux/rune_keeps_switching_back_to_an_old_saving_need/), [4](https://www.reddit.com/r/leagueoflegends/comments/tkp4il/i_have_a_problem_with_the_rune/), [5](https://www.reddit.com/r/leagueoflegends/comments/tokmc3/whats_the_point_of_having_rune_pages/)

There is no official solution as of now. Several suggested workarounds: [1](https://www.reddit.com/r/leagueoflegends/comments/soyl6p/comment/i08hg4c/?utm_source=share&utm_medium=web2x&context=3), [2](https://www.reddit.com/r/leagueoflegends/comments/soyl6p/comment/hybxcxc/?utm_source=share&utm_medium=web2x&context=3), [3](https://www.reddit.com/r/leagueoflegends/comments/stn1ux/comment/hx5g2v6/?utm_source=share&utm_medium=web2x&context=3), [4](https://www.reddit.com/r/leagueoflegends/comments/soyl6p/comment/i1wcfa5/?utm_source=share&utm_medium=web2x&context=3)
Many of them seem easy enough to be incorporated into the script.

**Comment by kyechou** [comment]
The added workaround is working now, so I'm closing the issue for the time being. We may want to disable the workaround once Riot fixes the problem officially. Please feel free to reopen the issue if it doesn't work.
