### ISSUE TITLE
is wine-lol bug fix in upstream?

### ISSUE THREAD

**Issue by barfin** [kyechou/leagueoflegends#4]
I asked this in AUR but didn't get any response
this bug was fixed and it says the same thing (crashing after champion selection)
https://bugs.winehq.org/show_bug.cgi?id=48138
but I'm not sure if it's the exact same bug that is fixed in wine-lol

**Comment by kyechou** [comment]
Hi @barfin, last time I checked (a few weeks ago) the issue still exists, so I guess not.
