### ISSUE TITLE
Can't start launcher

### ISSUE THREAD

**Issue by SemnoSao** [kyechou/leagueoflegends#43]
### System information

[System]
OS:              Manjaro Linux 21.2.5 Qonos
Arch:            x86_64
Kernel:          5.13.19-2-MANJARO
Desktop:         XFCE
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 3600X 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             31.3 GB
Swap:            17.1 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 580 Series (POLARIS10, DRM 3.41.0, 5.13.19-2-MANJARO, LLVM 13.0.1)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 21.3.7
OpenGL Core:     4.6 (Core Profile) Mesa 21.3.7
OpenGL ES:       OpenGL ES 3.2 Mesa 21.3.7
Vulkan:          Supported

### Describe the issue

When running `leagueoflegends start` the launcher window doesn't appear at all or blinks really fast and disapear. I also have a forever running loading window with "Waiting for the league client port to open".

sometimes I get a error message like this:
```
Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  10 (X_UnmapWindow)
  Resource id in failed request:  0x9600001
  Serial number of failed request:  1457
  Current serial number in output stream:  1458
```

but most times I just get no log at all. Just "[+] Starting..." and then nothing more beside the loading waiting port window.

**Comment by SemnoSao** [comment]
I could get it to open by running "leagueoflegends kill" and the starting again. The window "waiting for port" disappears when the game launcher loads (not the login window). Sorry for the inconvenience.

**Comment by kyechou** [comment]
No problem. Glad it works now!
