### ISSUE TITLE
Errors installing

### ISSUE THREAD

**Issue by Naginipython** [kyechou/leagueoflegends#47]
### System information

 - Distro: [e.g. Arch, Ubuntu 20.04, Fedora 35]
 - DE/WM: [e.g. Gnome, KDE, i3, bspwm]
 - CPU: [e.g. Intel i7-9750H]
 - GPU: [e.g. GTX 1080 Ti]
 - Graphics card drivers installed: [e.g. `mesa`, `xf86-video-intel`, `nvidia`, `xf86-video-nouveau`]

If your issue is related to graphics display, please attach the output of `vulkaninfo --summary`.

### Describe the issue

When running `leagueoflegends install` I get the error:
`Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org`
and 
`libgcc_s.so.1 must be installed for pthread_cancel to work
wine client error:4c: libgcc_s.so.1 must be installed for pthread_cancel to work
wine client error:50: write: Bad file descriptor`
I can confirm that I have "lib32-gcc-libs", "gcc-libs", and freetype2 libraries. 

### Screenshots

![Screenshot_20220428_091323](https://user-images.githubusercontent.com/42967504/165760463-7bedbf6a-45f6-411d-8c5d-54d3964b3c90.png)
![Screenshot_20220428_091335](https://user-images.githubusercontent.com/42967504/165760472-0f5af5ae-a025-43c5-8329-42344f595005.png)
![Screenshot_20220428_091343](https://user-images.githubusercontent.com/42967504/165760481-3975146f-062d-4fbd-84ab-c6db3c36fe99.png)
![Screenshot_20220428_091348](https://user-images.githubusercontent.com/42967504/165760489-2bf20a73-86ce-49f8-ab42-4886b8192827.png)

**Comment by kyechou** [comment]
Hi @Naginipython, please fill out the system information.

- Distro: [e.g. Arch, Ubuntu 20.04, Fedora 35]
- DE/WM: [e.g. Gnome, KDE, i3, bspwm]
- CPU: [e.g. Intel i7-9750H]
- GPU: [e.g. GTX 1080 Ti]
- Graphics card drivers installed: [e.g. mesa, xf86-video-intel, nvidia, xf86-video-nouveau]

For the FreeType font issue, please try https://forums.lutris.net/t/solved-wine-missing-freetype-library/2772.
For the `libgcc_s.so.1` issue, please make sure the relevant packages are installed on your system and the file is present. If it still doesn't work, try using LD_PRELOAD or LD_LIBRARY_PATH. Ref: https://github.com/ninia/jep/issues/227, https://github.com/actions/virtual-environments/issues/2803.
And if it works, please let me know your system information and the required packages. Thanks!

**Comment by Naginipython** [comment]
My apologies, I tend to mess up my Linux and reinstall very often, and I haven't had this issues since. However, in hindsight, I believe the reason I had this issue was possibly due to misunderstanding what wine-lol was. I never actually installed wine-lol I believe, I think I was confused and simply modified wine and thought doing that made it wine-lol. Thanks for the response though!
