### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by xTarzx** [kyechou/leagueoflegends#48]
Before creating an issue, please take a look at the [troubleshooting
section](https://old.reddit.com/r/leagueoflinux/wiki/index#wiki_3_-_.1F527_tech_support_and_troubleshooting).

### System information

 - Distro: arch
 - DE/WM: kde plasma (wayland), kwin
 - CPU: Intel i5-9300H
 - GPU: GTX 1050
 - Graphics card drivers installed: nvidia

### Describe the issue

`leagueoflegends install` fails to import dlls

### Steps to reproduce

run `leagueoflegends install`

["leagueoflegends -v install" output](https://gist.github.com/xTarzx/81ae443e6d3600fb2c9df6dccf8fbcf6)

**Comment by kyechou** [comment]
Hi @xTarzx, I couldn't find information related to the problem, especially during `wineboot --init`. I have no idea what might be the cause. Could you please do a system upgrade, clean reboot, and then run
```
leagueoflegends reinstall
```
and see what happens?

**Comment by xTarzx** [comment]
> Hi @xTarzx, I couldn't find information related to the problem, especially during `wineboot --init`. I have no idea what might be the cause. Could you please do a system upgrade, clean reboot, and then run
> 
> ```
> leagueoflegends reinstall
> ```
> 
> and see what happens?

I tried to reinstall all dependencias but issue still persisted.

Will be closing this issue since it seems I'm the only one with this problem.
Possibly going to try again after a clean OS install.

**Comment by xTarzx** [comment]
For anyone getting the same error, i managed to workaround it.

Use another wine (not wine-lol) to initialize the prefix.
Then `leagueoflegends install` should work.
