### ISSUE TITLE
Increasing the launch speed of the client

### ISSUE THREAD

**Issue by emrebicer** [kyechou/leagueoflegends#49]
### System information

 - Distro: `Arch`
 - DE/WM: `i3`
 - CPU: `AMD Ryzen 5 1600 (12) @ 3.200GHz`
 - GPU: `NVIDIA GeForce GTX 1070`
 - Graphics card drivers installed: `nvidia`

### Describe the issue
Currently, after executing the command `leagueoflegends start` there is around 5 minutes of delay until we see the actual league client. I think this issue has been around for a very long time and it exists across other league laucher wrappers. 

It seems like there is a hacky solution to get rid of this issue. The solution is posted and pinned at the [r/leagueoflinux](https://www.reddit.com/r/leagueoflinux) subreddit and the post can be found [here](https://www.reddit.com/r/leagueoflinux/comments/srn0wt/future_is_now/). As I understand the solution is instructed for Lutris launcher, but I am wondering if it would be possible to use it in this project as well or even if it would be a good idea.

**Comment by kyechou** [comment]
Hi @emrebicer, thanks for letting me know! I saw the post some time ago. But there are concerns that the code injection may result in bans from Riot, because it's technically a third-party client, so I decided not to use it by default. If you're interested in using the solution, perhaps try https://www.reddit.com/r/leagueoflinux/comments/toagve/easy_guide_for_kyechous_leagueoflegends_no/.

**Comment by Miusaky** [comment]
Perhaps worth re-considering now. It's been out for a few months with no reports of bans and the Lutris script seems to now have adopted it as well.

**Comment by Ltrinch** [comment]
To optimize LoL loading, just run $CLIENT_EXE without 
`--launch-product=league_of_legends --launch-patchline=live` 
and remove/comment 
`( port_waiting_daemon ) | loading_screen &`, then LoL will start faster (around 20-40 second).
After the LoL client is loaded, close the Riot client.

**Comment by kyechou** [comment]
The script and README are updated and tested with the new wine-lol.
