### ISSUE TITLE
Skarner champion causing frame drops

### ISSUE THREAD

**Issue by asamwow** [kyechou/leagueoflegends#5]
Hi, I don't own skarner unfortunately, but I think some code of his causes massive frame drops. Could easily have to do with the domination objectives he creates.
I played 2 games against him as nasus, and it was as if I had 10 fps, while usually I get 180+
I had no other applications open. nvidia drivers, amd cpu, manjaro.

Thanks a lot for having the most convenient way of playing lol on linux btw.

**Comment by asamwow** [comment]
I get the exact same issue in nexus blitz every game.

**Comment by kyechou** [comment]
Hi @asamwow, thanks for bringing it up. Unfortunately I don't have Skarner either. Also I'm a bit occupied recently, and probably not able to look into it until later this fall or winter, so it would be nice if in the mean time someone could try it out or report it to the upstream accordingly.

**Comment by asamwow** [comment]
issue doesn't exist when I tried using Lutris

**Comment by kyechou** [comment]
Hi @asamwow, I just updated the install and launch script to use the new Riot client. Could you try the new revision and see if it works? Thanks!
