### ISSUE TITLE
Client closes and re-launches itself during champion select. 

### ISSUE THREAD

**Issue by Miusaky** [kyechou/leagueoflegends#51]
### System information

 - Distro: Void Linux
 - DE/WM: dwm
 - CPU: AMD Ryzen 5 5600X
 - GPU: NVIDIA GeForce GTX 1080
 - Graphics card drivers installed: Nvidia 515.48.07_1

### Describe the issue

Client quits and re-launches itself repeatedly during champion select. Works fine until the queue has been accepted. It does not happen all the time - sometimes I can enter a match and have no problems - but it is frequent. 

### Steps to reproduce
1. Queue
2. Accept
3. Wait

### Log
https://pastebin.com/ZDQ72Adv

What could be causing this?

**Comment by kyechou** [comment]
Hi @Miusaky, sorry that I've been busy lately and couldn't take a look at the issue. I'm wondering if the issue is resolved? If so, how was it resolved?

**Comment by kyechou** [comment]
Cool, glad it worked!  Please feel free to submit new issues if there's one.
