### ISSUE TITLE
Speed up the LoL loading process w/o any program

### ISSUE THREAD

**Issue by Ltrinch** [kyechou/leagueoflegends#52]
### System information

 - Distro: Gentoo 2.8
 - DE/WM: i3
 - CPU: Intel i5-8400
 - GPU: UHD 630
 - Graphics card drivers installed: `mesa`, `xf86-video-intel`
### Describe the issue

League of Legends takes a very long time to start (5+ minutes).

### Steps to reproduce

1. Run command `leagueoflegends start`
2. Wait 5 minute (???)
3. Done.
### How to fix it

The only thing is that you have to run LoL through the Riot Client, but that's much faster than running it through a command. While loading the client, I do not recommend to move/close the Riot Client, close it after loading the LoL client.

(Unfortunately, I can't test it on Garena, and I'm not sure if it works on it, need to check.
If you want to test this on Garena, just comment out [1.])
**Remove:** 
1. `( port_waiting_daemon ) | loading_screen &`    | 387 line
2.  | 332 line
```bash
port_waiting_daemon() {
    # Find PID
    process=LeagueClientUx.exe
    uxpid=$(timeout 2m sh -c "until ps -C $process -o pid=; do sleep 1; done | sed 's/[[:space:]]*//g'")
    if [ -z "$uxpid" ]; then
        die "Could not find process ${process}"
    fi

    # Get the app-port parameter
    port=$(xargs -0 <"/proc/${uxpid}/cmdline" | sed -n 's/.*--app-port=\([[:digit:]]*\).*/\1/p')
    if [ -z "$port" ]; then
        die "Could not find --app-port of LeagueClientUx.exe"
    fi

    # Suspend the league client until app-port gets available
    kill -STOP ${uxpid}
    timeout 5m bash -c "
    until openssl s_client -connect :${port} <<< Q >/dev/null 2>&1; do
        sleep 1
    done"
    kill -CONT ${uxpid}
}
```
Edit in start_LoL(): | 391 line
```bash
wine "$(winepath -w "$CLIENT_EXE")" \        -> wine "$(winepath -w "$CLIENT_EXE")"  
        --launch-product=league_of_legends \ -> 
        --launch-patchline=live              ->
```

[Proof](https://streamable.com/ukj9ib) that it really works.

**Comment by F1uk369** [comment]
my league just doesnt start reguardless. mind sharing the script? i may of broken something.

**Comment by calebaden** [comment]
this doesn't work for me either

**Comment by Ltrinch** [comment]
> my league just doesnt start reguardless. mind sharing the script? i may of broken something.
Hm... try this?..
https://pastebin.com/LUn7WNAe

**Comment by Ltrinch** [comment]
You can also just cp this changes and test it 
https://github.com/kyechou/leagueoflegends/pull/54/files

**Comment by kyechou** [comment]
The script and README are updated and tested with the new wine-lol.
