### ISSUE TITLE
New WINE patch to get rid of vsyscall32=0 problems

### ISSUE THREAD

**Issue by kassindornelles** [kyechou/leagueoflegends#55]
Hi!
Theres a new patch for WINE that fixes the need for the vsyscall32=0 problem
So using the new builds provided by GE (and in the future by M-Reimer) would fix all the issues like lower 32-bit performance by using vsyscall32=0 system wide!

also worth saying that the GloriousEggroll builds also fix the need for a script to launch league, so you can just run the riotclientservices.exe directly without any .sh script or anything else, i believe M-Reimer wine-lol build do or will do the same (i'm not sure because i normally use lutris wine builds)

all the information you need is here:
https://github.com/M-Reimer/wine-lol/issues/109
and here
https://www.reddit.com/r/leagueoflinux/comments/w97wr4/lutrisge703lol_released_fixes_abivsyscall320/

**Comment by Kitt3120** [comment]
Nice to see an issue already open, just wanted to open one up! :)
The new GloriousEggroll build also fixes the long start up time of about 5 minutes! The client starts very quick now, just as on Windows.

**Comment by M-Reimer** [comment]
Fixed in "wine-lol" and now we also have a "wine-lol-bin" PKGBUILD.

@kyechou I'm not sure what we should do with your "wine-ge-lol" PKGBUILD now. Do you want to request deletion for it?

**Comment by kyechou** [comment]
Hi, sorry for the late reply. Life's been demanding lately.

@kassindornelles Thanks for the information and I'm glad the issue's resolved in wine! I'll update the scripts and resolve related issues this morning or over the weekend.

@M-Reimer Yeah I think that's the way to go. I'll test the game soon and send out the deletion request for wine-ge-lol.

**Comment by kyechou** [comment]
The script and README are updated and tested.
