### ISSUE TITLE
League of Launcher not responding

### ISSUE THREAD

**Issue by johny135795** [kyechou/leagueoflegends#56]
The process acted as the creators told him to. I log in and run until the Riot launcher, but the League of Legends launcher does not run I don't know what the problem is.
just unresponsive

**Comment by kyechou** [comment]
Hi @johny135795, please provide more information like the verbose output of running the game (start it with the `-v` option), the system information (distro, GPU, graphics driver packages, etc.), how exactly you installed the game, and then double-check if all the dependencies and drivers are correctly installed.

**Comment by johny135795** [comment]
I'm using Fedora 36. https://github.com/kyechou/leagueoflegends
It seems that all the parts included in the code were installed in .
01:00.0 VGA compatible controller: Advanced

My current computer is cpui5-14000F
The Gpu is an RTX 570 RX.
Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (rev ef)

I followed the installation method according to the code and implemented it.

**Comment by johny135795** [comment]
Currently, I'm enjoying the game by installing it as a snap, but it sometimes turns off or freezes once in every game. This phenomenon seems to be happening.

**Comment by johny135795** [comment]
Riot launcher runs, but the role client itself does not (no response)

**Comment by kyechou** [comment]
#59
