### ISSUE TITLE
League client freezes (blanking on or before the honors page) after a game finishes

### ISSUE THREAD

**Issue by kyechou** [kyechou/leagueoflegends#57]
### System information

 - Distro: Arch Linux (5.18.16.arch1-1)
 - DE/WM: bspwm
 - CPU: Intel i7-9750H
 - GPU: GeForce RTX 2060
 - Graphics card drivers installed: `mesa`, `nvidia-dkms`, `nvidia-utils`, `lib32-nvidia-utils`

### Describe the issue

After each match ends, around 80-90% of the time the League client freezes during/before the honors page.

### Steps to reproduce

1. Play a game as usual.
2. Click on "continue" upon victory/defeat.
3. League client freezes.

### Related issues and potential workaround

* https://www.reddit.com/r/leagueoflinux/comments/jlczr9/client_saying_game_still_in_progress_postmatch/
* https://www.reddit.com/r/leagueoflinux/comments/jjjxjb/client_breaks_after_every_game/
* https://www.reddit.com/r/leagueoflinux/comments/wmjvvo/league_client_crashesbecomes_unresponsive_after/
  * Workaround: Revert `wine-lol` back to 7.0.4 (with GE patches).
* https://www.reddit.com/r/leagueoflinux/comments/wm36iq/anyone_else_experiencing_very_long_load_times/
* https://www.reddit.com/r/leagueoflinux/comments/wofums/comment/ikavi5u/?utm_source=share&utm_medium=web2x&context=3

**Comment by kyechou** [comment]
Fixed: https://github.com/M-Reimer/wine-lol/pull/112.

**Comment by rurigk** [comment]
This has the 5 minute wait or everything is already fixed (5 minute wait + Hang after game)?
