### ISSUE TITLE
Can't install due to "modify_ldt: Function not implemented"

### ISSUE THREAD

**Issue by Phanatik** [kyechou/leagueoflegends#58]
### System information

 - Distro: Arch Linux (linux-hardened 5.18.17.hardened1-1)
 - DE/WM: Sway
 - CPU: Ryzen 7 3700X
 - GPU: Sapphire Radeon RX5700 XT
 - Graphics card drivers installed: [e.g. `mesa`, `lib32-mesa`, `vulkan-radeon`, `lib32-vulkan-radeon`]

### Describe the issue

When attempting to install League of Legends (or even use wine-lol at all), results in a modify_ldt error.

### Steps to reproduce

1. Install `leagueoflegends-git`: `yay -S leagueoflegends-git`
2. Wait for dependency and package install
3. Install prefix: `leagueoflegends -v install`
4. Returns error `modify_ldt: Function not implemented`

```
$ leagueoflegends -v install
+ export WINEDEBUG=fixme-all
+ WINEDEBUG=fixme-all
+ export VK_LOADER_DEBUG=all
+ VK_LOADER_DEBUG=all
+ shift
+ :
+ case "${1-}" in
+ break
+ case "${1-}" in
+ install_LoL
+ '[' '!' -d /home/user/.local/share/leagueoflegends ']'
+ '[' -f '/home/user/.local/share/leagueoflegends/drive_c/Riot Games/Riot Client/RiotClientServices.exe' ']'
+ askQ 'Select your region' 'North America' 'EU West' 'EU Nordic & East' 'Latin America North' 'Latin America South' Brazil Turkey Russia Japan Oceania 'Republic of Korea'
+ count=1
+ echo
+ echo '    Select your region'
+ shift
+ for region in "$@"
+ echo '    #1 - North America'
+ (( count++ ))
+ for region in "$@"
+ echo '    #2 - EU West'
+ (( count++ ))
+ for region in "$@"
+ echo '    #3 - EU Nordic & East'
+ (( count++ ))
+ for region in "$@"
+ echo '    #4 - Latin America North'
+ (( count++ ))
+ for region in "$@"
+ echo '    #5 - Latin America South'
+ (( count++ ))
+ for region in "$@"
+ echo '    #6 - Brazil'
+ (( count++ ))
+ for region in "$@"
+ echo '    #7 - Turkey'
+ (( count++ ))
+ for region in "$@"
+ echo '    #8 - Russia'
+ (( count++ ))
+ for region in "$@"
+ echo '    #9 - Japan'
+ (( count++ ))
+ for region in "$@"
+ echo '    #10 - Oceania'
+ (( count++ ))
+ for region in "$@"
+ echo '    #11 - Republic of Korea'
+ (( count++ ))
+ echo
+ read -r -p '    #: ' answer
    #: 2

+ case "${answer}" in
+ export LANG_CODE=euw
+ LANG_CODE=euw
+ INSTALLER=/home/user/.cache/leagueoflegends/installer.euw.exe
+ INSTALLER_URL=https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.euw.exe
+ '[' '!' -e /home/user/.cache/leagueoflegends/installer.euw.exe ']'
+ msg 'Installing League of Legends...'
+ echo -e '[+] Installing League of Legends...'
[+] Installing League of Legends...
++ winepath -w /home/user/.cache/leagueoflegends/installer.euw.exe
modify_ldt: Function not implemented
err:seh:segv_handler_early Got unexpected trap 13 during process initialization
+ wine ''
modify_ldt: Function not implemented
err:seh:segv_handler_early Got unexpected trap 13 during process initialization```

**Comment by kyechou** [comment]
Hi @Phanatik, thanks for the issue. What's the output of `zcat /proc/config.gz | grep MODIFY_LDT` in your system? I suspect this may have something to do with the hardened kernel. This [post](https://bbs.archlinux.org/viewtopic.php?id=234698) also seems relevant.

**Comment by Phanatik** [comment]
> Hi @Phanatik, thanks for the issue. What's the output of `zcat /proc/config.gz | grep MODIFY_LDT` in your system? I suspect this may have something to do with the hardened kernel. This [post](https://bbs.archlinux.org/viewtopic.php?id=234698) also seems relevant.

It might have something to do with the change in wine-lol to use GloriousEggroll's patches because it used to work before and then suddenly stopped. 

`zcat /proc/config.gz | grep MODIFY_LDT`

Gives me: ```# CONFIG_MODIFY_LDT_SYSCALL is not set```

**Comment by kyechou** [comment]
Yeah, the switch to GloriousEggroll's patch set definitely changes a few requirements for running the game in wine-lol.  It looks like there's no easy fix (AFAIK) other than either rebuild the kernel while enabling the kernel options mentioned [here](https://bugs.archlinux.org/task/57440), or switch to another kernel package (e.g., `linux`).

**Comment by Phanatik** [comment]
Well that's rubbish. It was the only way I could get the game to work. Lutris refused to install the prefix but that's a separate issue. I guess I'll close this for now then. 

Thank you for the help and info!
