### ISSUE TITLE
Replays were incorrectly merged!

### ISSUE THREAD

**Issue by BeetMacol** [kyechou/leagueoflegends#66]
Hi, yesterday you merged my replay PR (#65).

Before merging, you made a few changes and one of them **breaks the replay command** (at least for me)! The League of Legends game EXE does not work when started from outside its directory - that's why I added the `pushd` and `popd` lines.

## The issue
After running `leagueoflegends replay replay.rofl`, League of Legends logs the following error, and a popup is displayed before crashing.
```
League of Legends.exe(00000144): ALWAYS| Wrote soft repair file to Z:\home\macol\documents\League of Legends\Replays/../SOFT_REPAIR. This will cause the patcher to repair your installation.
League of Legends.exe(00000144):  ERROR| ALE-18967991 FATAL ERROR - Installation is corrupt. WadFile mount failed.
 - WadFile: DATA/FINAL/Bootstrap.windows.wad.client
 - Problem: Missing
```

## Suggested change

The **line 354**:
```bash
    wine "$(winepath -w "$GAME_EXE")" "$(winepath -w "$1")"
```
should be changed back to my **original code**:
```bash
    replayPath=$(winepath -w "$1")
    pushd "$GAME_EXE_DIR"
    exec wine "$(winepath -w "$GAME_EXE")" "$replayPath"
    popd
```

**Comment by kyechou** [comment]
Thank you @BeetMacol!

**Comment by BeetMacol** [comment]
It's almost fine now. This time though, relative replay paths will not work correctly as you change the directory before `$(winepath -w "$1")`... It should be perfectly fine for absolute paths.

**Comment by BeetMacol** [comment]
Yeah, seems to be fine now. Sorry for late reply.
Thank you for adding the feature!
