### ISSUE TITLE
Pre-Launch script needed to successfully start LoL

### ISSUE THREAD

**Issue by M-Reimer** [kyechou/leagueoflegends#7]
Since a few weeks there is an issue where the client runs into a timeout as for some reason a part of the LoL client runs way too slow with Wine.

There is a workaround with a pre-launch script which suspends the LoL client until the required port gets available:

https://www.reddit.com/r/leagueoflinux/comments/j07yrg/starting_the_client_script/

I did a few minor fixes to this script. My fixed version can be found here:

https://github.com/M-Reimer/leagueoflegends-linux/blob/master/lol-launchhelper.sh

The most important change is replacing "/bin/sh" with "/bin/bash" because of bashism used in the script.

The script has to be called in background before executing the actual LoL client.

**Comment by kyechou** [comment]
Wow, @M-Reimer thanks a lot! I will try it out and update it ASAP.

**Comment by kyechou** [comment]
I tried it out this evening (and I also tried a few variations of the script with uninstalling and installing everything), but the issue still exists. I will probably need to come back to it later when I have more time, and so if anyone has time to investigate the solution, PRs are welcome.

**Comment by M-Reimer** [comment]
Maybe it would help if you find out where the script fails. It should wait for the LoL client to become available and then suspend it. If one of the steps fails, maybe the script still needs some work.

**Comment by travis-tang** [comment]
It seems to work with the new riot client instead of the old client. But how to get the new client?

**Comment by kyechou** [comment]
I've just updated the scripts with the new client and the launch helper, and tested successfully on my setup. Close for now. Feel free to re-open the issue (or new issues) if there's any trouble.
