### ISSUE TITLE
League of Legends client crashes at launch.

### ISSUE THREAD

**Issue by Bligzar** [kyechou/leagueoflegends#70]
### System information

I have 2 machines :
 - Distro: Arch 6.0.9 / Manjaro 5.15 LTS
 - DE: KDE Wayland / X11
 - CPU: Ryzen 7 1700 / Ryzen 7 6850U
 - GPU: AMD 680M / NVidia 1060 6GB
 - Graphics card drivers installed:  libvulkan_radeon/ libGLX_nvdia

Both are on fresh leagueoflegends-git install from yay/pamac

### Describe the issue

The league of legends client crashes a couple of minutes after the LoL logo appears incorrectly rendered.

### Steps to reproduce

1. Run command : 'leagueoflegends -v start'
2. Proceed into the Riot Client to launch the League of Legends Client
3. The League of Legends logo appears but doesn't render correctly (Like it did before with the launch delay)
4. After a few minutes the client crashes and brings back the Riot Client.
5. There is no new entries in the log when the crash happens.

### Screenshots
![image](https://user-images.githubusercontent.com/1369711/203469812-c4eeab62-023d-443c-b6ff-6ffec655afab.png)

### Logs
https://gist.github.com/Bligzar/9ec02a5c6a1475da0fac1cbceee68258

**Comment by kyechou** [comment]
Please attach the complete log output of `leagueoflegends -v reinstall` and `leagueoflegends -v -s start`.

**Comment by Bligzar** [comment]
Here! : https://gist.github.com/Bligzar/9ec02a5c6a1475da0fac1cbceee68258
