### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by Jezda1337** [kyechou/leagueoflegends#84]
Before creating an issue, please take a look at the [troubleshooting
section](https://old.reddit.com/r/leagueoflinux/wiki/index#wiki_3_-_.1F527_tech_support_and_troubleshooting).

### System information

 - Distro: Nobara 37
 - DE/WM/Compositor: KDE
 - CPU:  AMD FX(tm)-6300 BE
 - GPU: GTX 1060
 - Graphics card drivers installed: Nvidia

If your issue is related to graphics display, please attach the output of `vulkaninfo --summary`.

### Describe the issue
leagueoflegends -v start otuput:
https://pastebin.com/bhv1yxtS

after I run the leagueoflegends start command, the client opens and I enter the login data into the game, I press the login button, the client shuts down and the lol logo is shown, after that everything freezes as far as the game is concerned, the system is still working. And I get this message in the terminal:

wine: Unhandled page fault on write access to 00000F0D at address F7E26527 (thread 076c), starting debugger...

A clear and concise description of what the issue is.

### Steps to reproduce

**Note:** Use the `-v` option and attach the verbose log outputs for all
relevant commands. For long texts/logs, consider sharing them via services like
[Gist](https://gist.github.com/). Please do not attach screenshots for text/log
outputs.

1. Run command leagueoflegends -v start
2. Login in but without sucess

### Screenshots
![Screenshot_20230405_145350](https://user-images.githubusercontent.com/42359294/230086366-8d741713-6091-4b17-bea8-fd7018a99916.png)

If applicable, add screenshots for the issue.

**Comment by imYurikhan** [comment]
Same issue here.
I'm on Nobara 37 too.

**Comment by imYurikhan** [comment]
I can add that if I install the game via Lutris, I can manage to start the launcher but got an error when I start a game

![error](https://user-images.githubusercontent.com/77806690/230088627-f84d9eda-6248-4857-9e24-43edf8bd5e34.png)

**Comment by Jezda1337** [comment]
I encounter the same issue using lutris, and reading r/leagueoflinux I saw this post and wanna try this script. Hope lutris script will get update soon.

**Comment by kyechou** [comment]
Hi @Jezda1337, the attached log output is not the entire output. Please share the *entire* output so that we might know what went wrong.

Also, how did you guys install wine-lol on Fedora or Nobara?

**Comment by Abdulee** [comment]
I've it installed via lutris script as thats what i was using previously

**Comment by Jezda1337** [comment]
hey man, @kyechou here is the full log https://pastebin.com/H3NSigdq sry for the  prev one :) 
bdw I jump into ur script just to see where  do you trying to get wine-lol and notice the patn /opt/wine-lol/bin, when I check that path on my machine, there wasn't any. So I went to [here](https://github.com/GloriousEggroll/wine-ge-custom/releases?q=-LoL&expanded=true) and grab the latest relese, extract it into /opt/wine-lol/ and now I  have seam problem as #85.
I run the command leagueoflegends run which wine and the output was /opt/wine-lol/bin/wine. 
I hope this will help, and If I install wine-lol wrong way pls provide solution, thanks!

**Comment by kyechou** [comment]
Hi @Jezda1337, nice! So it's basically the same issue then. And you're right. There's no easy way to install wine-lol currently for non-Arch based distros (except for maybe downloading the binaries from wine-ge-custom). Unfortunately I don't have spare hardware with GPUs and time to work on building/distributing .deb or .rpm packages. But that'd be nice to have. Maybe later when the game is working I might try to do that.

Closing for now. Duplicate #83, #85.
