### ISSUE TITLE
"Update server down" when running install

### ISSUE THREAD

**Issue by g1sbi** [kyechou/leagueoflegends#87]
### System information

 - Distro: Arch
 - DE/WM/Compositor: bspwm + picom
 - CPU: Ryzen 5 5600
 - GPU: Nvidia RTX 2060 Super
 - Graphics card drivers installed: `nvidia-dkms`

If your issue is related to graphics display, please attach the output of `vulkaninfo --summary`.

### Describe the issue

When trying to install, the installer doesn't open and a "Update server down" error appears

### Steps to reproduce

- run `leagueoflegends install`
- select `EU West`
- the installer shows the "Update server down" error

### Screenshots

![image](https://user-images.githubusercontent.com/68223680/230148784-d4cf2a8e-1ea4-49ac-ae44-4641dd7c31e9.png)

**Comment by kyechou** [comment]
Hi @g1sbi, it looks like Riot's servers were down and it doesn't seem to be related to the script. So I'm closing this for now, unless new information suggests otherwise.

**Comment by g1sbi** [comment]
@kyechou retried multiple times, still down, but works fine on Windows. Are there any logs I can send you to troubleshoot?

**Comment by kyechou** [comment]
1. Run `leagueoflegends uninstall`
2. Output of `pacman -Qi leagueoflegends-git`
3. Output of `leagueoflegends -v install`
4. Output of `leagueoflegends -v start`

Please send the output of 2, 3, 4 if the same error still exists.
