### ISSUE TITLE
Network activity from LoL causing router to crash

### ISSUE THREAD

**Issue by bbarnes11** [kyechou/leagueoflegends#89]
System information

    Distro: [Arch
    DE/WM/Compositor: Gnome
    CPU: Ryzen 1600
    GPU: RX480
    Graphics card drivers installed: mesa, vulkan-radeon

Issue Description
installer / client downloading updates causes PFsense to think its under attack and router shuts off WAN port

Steps to reproduce

Install script 'yay -S leagueoflegends-git'
Run install command 'leagueoflegends install'

**Comment by kyechou** [comment]
I doubt there is anything that can done by the launch script. What the installer and the client download is completely up to Riot. At the system level, the user may choose to use VPN, rate-limiter, or other networking solutions, but it's out of scope for this project.

Closing for now. Please reopen if (a) there are other people able to reproduce the problem and (b) there is new information about potential causes indicating that a common solution is suitable to be implemented as part of the launcher.
