### ISSUE TITLE
Feature request: Allow easy installing and running clients for multiple regions

### ISSUE THREAD

**Issue by NebuPookins** [kyechou/leagueoflegends#95]
Would be great if we could run `leagueoflegends install na` or `leagueoflegends install euw` or something along those lines to install different clients for different regions (perhaps in subdirectories of `~/.local/share`), and then `leagueoflegends play na`, `leagueoflegends play euw`, and so on, to launch those clients.

**Comment by kyechou** [comment]
Hi @NebuPookins

I've recently added a few options that achieve similar results.  You may use `--region` and `--locale` options to specify the arguments, and use `-f|--config <config/file/path>` to specify the install locations. Please see `leagueoflegends -h` for more. I haven't updated the README yet but I'll do so when I can.

For example:

```sh
$ leagueoflegends --region na --config ~/.config/league-na.sh install
$ leagueoflegends --region na --config ~/.config/league-na.sh start

# or

$ leagueoflegends --region euw --config ~/.config/league-euw.sh install
$ leagueoflegends --region euw --config ~/.config/league-euw.sh start
```

where the config files may look like:

```sh
$ cat ~/.config/league-na.sh
DATA_HOME=~/.local/share/leagueoflegends-na

$ cat ~/.config/league-euw.sh
DATA_HOME=~/.local/share/leagueoflegends-euw
```

If you want, you may even skip the `-f|--config` options and use the same wine prefix for installing/playing the different regions.
