### ISSUE TITLE
Segfault when running leagueoflegends start

### ISSUE THREAD

**Issue by HBBrennan** [kyechou/leagueoflegends#96]
Before creating an issue, please take a look at the [troubleshooting
section](https://old.reddit.com/r/leagueoflinux/wiki/index#wiki_3_-_.1F527_tech_support_and_troubleshooting).

### System information

 - Distro: Arch
 - DE/WM/Compositor: bspwm
 - CPU: Ryzen 3700k
 - GPU: 2080 super
 - Graphics card drivers installed: nvidia-dkms
 - Shell: zsh
 - Bash Version: GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
If your issue is related to graphics display, please attach the output of `vulkaninfo --summary`.

### Describe the issue
Part of the script, ```winepath -w $RIOT_CLIENT```, returns an empty string causing a sefault.

### Steps to reproduce
```
leagueoflegends start
```
results in:
```
/usr/bin/leagueoflegends: line 371: 19657 Segmentation fault      (core dumped) wine "$(winepath -w "$RIOT_CLIENT")" --launch-product=league_of_legends --launch-patchline="$PATCHLINE"
```

When I change the script to set -eux, I can see that ```winepath -w $RIOT_CLIENT```, returns an empty string causing a segfault. If I set $RIOT_CLIENT myself and run ```winepath -w $RIOT_CLIENT```, I get the correct path. I don't know why this is not working within the script.

**Comment by kyechou** [comment]
That's interesting. But unfortunately I'm not able to reproduce the issue at my end. More information would be helpful.

Also, is it possible that it has something to do with zsh?

**Comment by kyechou** [comment]
Hi @HBBrennan,
I'm closing the issue for now due to inactivity and it not being reproducible. Please feel free to open the issue if the problem persists and please provide the output of `leagueoflegends -v start` (or install). Thanks!
